color: null
fieldLayouts:
  d9836349-69b9-4d41-9ad2-99251bbd7240:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-19T13:07:31+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2094b60a-1761-4db4-820a-1c292c67dc61
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 20252c82-4bb7-4e7c-a4ae-0e4aeb054b99
        userCondition: null
handle: articleCategories
hasTitleField: true
icon: ''
name: 'Article Categories'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
