color: null
fieldLayouts:
  e29b7582-f2ef-4001-9526-8b02670390e1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-17T12:27:28+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: aade253d-6b6e-4234-aa8b-268b128301a5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-17T12:30:26+00:00'
            elementCondition: null
            fieldUid: 84283218-957b-4c9d-a1d9-ed73c435cde8 # Image
            handle: featuredImage
            includeInCards: false
            instructions: null
            label: 'Featured Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 348cb371-e741-40d8-8de2-7f9e5e52f16b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-17T12:30:26+00:00'
            elementCondition: null
            fieldUid: 96afe1ed-1049-4810-88fc-7c06133c2e03 # RTE - Full
            handle: articleContent
            includeInCards: false
            instructions: null
            label: Content
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae87fd90-01de-4481-8a16-9f37c31bac3f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 225a0598-4c01-4afe-b7a5-09de6618436c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-17T12:30:26+00:00'
            elementCondition: null
            fieldUid: 067dc454-76f0-47fe-8a39-6380da7fc55e # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 13e6820a-239b-4667-9845-4cb3b10b89ab
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 98702a96-b0d4-4b1f-8809-4a2d30b793dc
        userCondition: null
handle: articleNews
hasTitleField: true
icon: ''
name: 'Article & News'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
