color: green
fieldLayouts:
  9b463f61-7c92-42ca-ab20-12e22a17d013:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-18T05:23:59+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Section Heading'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: af52df04-f393-4f0b-b76c-f149002d64b2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-18T05:28:16+00:00'
            elementCondition: null
            fieldUid: b7b36318-f071-4097-8730-a77ac7b5fe96 # RTE - Simple Text
            handle: staticCardText
            includeInCards: false
            instructions: null
            label: 'Static Card Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc278004-1b75-4814-bda3-75f7857e843b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-18T05:28:16+00:00'
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'These cards will be shown from "Article & News" section'
            type: craft\fieldlayoutelements\Tip
            uid: e6f81313-78a7-4285-a58a-d3e1ce1c7af6
            userCondition: null
        name: Content
        uid: 6d4507bb-d6e4-40e5-8b03-aff1444d6e93
        userCondition: null
handle: articlesNewsSection
hasTitleField: true
icon: newspaper
name: 'Articles & News Section'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
