color: null
fieldLayouts:
  d223bc7b-0659-4abb-b040-f0ba3a4d17d5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-29T11:03:18+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Benefit Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c61a521b-18eb-49c5-aae4-2dd51c28bf7e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-29T11:06:33+00:00'
            elementCondition: null
            fieldUid: 84283218-957b-4c9d-a1d9-ed73c435cde8 # Image
            handle: benefitIcon
            includeInCards: false
            instructions: null
            label: 'Benefit Icon'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9b9e85d8-ec75-46e7-975f-a71e3d0bcf88
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-10-22T07:32:04+00:00'
            elementCondition: null
            fieldUid: b7b36318-f071-4097-8730-a77ac7b5fe96 # RTE - Simple Text
            handle: benefitText
            includeInCards: false
            instructions: null
            label: 'Benefit Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5f1b790-6a34-4f17-9846-fefafa83dec3
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2024-09-22T05:35:49+00:00'
            elementCondition: null
            fieldUid: aa88dbbd-c68f-44c0-bb5f-efd07e8cb367 # CTA
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 704df012-697c-4b90-aa88-e933930f6e2f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 54f40c7d-5e34-4318-9cdf-62366a5d7104
        userCondition: null
handle: benefits
hasTitleField: true
icon: table-list
name: Benefits
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
