color: null
fieldLayouts:
  d223bc7b-0659-4abb-b040-f0ba3a4d17d5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-29T11:03:18+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Benefit Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c61a521b-18eb-49c5-aae4-2dd51c28bf7e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-29T11:06:33+00:00'
            elementCondition: null
            fieldUid: 84283218-957b-4c9d-a1d9-ed73c435cde8 # Image
            handle: benefitIcon
            includeInCards: false
            instructions: null
            label: 'Benefit Icon'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9b9e85d8-ec75-46e7-975f-a71e3d0bcf88
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-08-29T11:06:33+00:00'
            elementCondition: null
            fieldUid: 8c2ae0e0-bafc-45d7-ac4b-2de4bd0cabec # Text Area
            handle: benefitText
            includeInCards: false
            instructions: null
            label: 'Benefit Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a57b400-fe7e-4bbd-ae3d-8144e7baccb0
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 54f40c7d-5e34-4318-9cdf-62366a5d7104
        userCondition: null
handle: benefits
hasTitleField: true
icon: table-list
name: Benefits
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
