color: null
fieldLayouts:
  812217c8-8acd-428e-b451-ace283d33713:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-22T05:15:39+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Card Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8d432e2f-52c2-4f88-8584-51ee57fdab30
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-22T10:24:36+00:00'
            elementCondition: null
            fieldUid: 7aea93d0-d819-4905-8279-efcfd692ad42 # Text
            handle: cardTitle
            includeInCards: false
            instructions: null
            label: 'Card Title'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c843c8fa-1f66-4fc3-9ad6-640ebbbac3f1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-22T06:55:59+00:00'
            elementCondition: null
            fieldUid: b7b36318-f071-4097-8730-a77ac7b5fe96 # RTE - Simple Text
            handle: cardText
            includeInCards: false
            instructions: null
            label: 'Card Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e22d625f-c604-43b8-9892-08df4f1dd151
            userCondition: null
            warning: null
            width: 100
        name: Card
        uid: 30720d45-3508-43d4-b58c-09bed9704a95
        userCondition: null
handle: card
hasTitleField: false
icon: ''
name: Card
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
