color: null
fieldLayouts:
  812217c8-8acd-428e-b451-ace283d33713:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-22T05:15:39+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Card Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8d432e2f-52c2-4f88-8584-51ee57fdab30
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-22T05:17:18+00:00'
            elementCondition: null
            fieldUid: 8c2ae0e0-bafc-45d7-ac4b-2de4bd0cabec # Text Area
            handle: cardText
            includeInCards: false
            instructions: null
            label: 'Card Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 15e7194a-698f-4944-9476-c1faacff394b
            userCondition: null
            warning: null
            width: 100
        name: Card
        uid: 30720d45-3508-43d4-b58c-09bed9704a95
        userCondition: null
handle: card
hasTitleField: true
icon: ''
name: Card
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
