color: emerald
fieldLayouts:
  a97bf110-6799-4c04-8426-0853163a9491:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-26T05:01:05+00:00'
            elementCondition: null
            fieldUid: 734fcaa6-5b7e-47f5-86ea-1d350cdfaecf # Embedded Asset
            handle: video
            includeInCards: false
            instructions: 'Embed video or upload video file.'
            label: Video
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 890f011c-e298-4c82-b387-00faf03e3052
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-22T05:51:23+00:00'
            elementCondition: null
            fieldUid: 64b3113c-4c07-47b2-bed6-94149314dc80 # RTE - Text Only
            handle: videoText
            includeInCards: false
            instructions: null
            label: 'Video Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93475d6f-f3d0-4019-9341-623626b58d4e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8c5e4b6d-5e30-4f9a-a2bf-b41b9b6b8562
        userCondition: null
handle: employeeVideo
hasTitleField: false
icon: user
name: 'Employee Video'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
