color: fuchsia
fieldLayouts:
  eef72a25-efe6-4a0f-9bda-c6de3a018d30:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-22T05:50:28+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a6bd1c90-5b5c-4b0d-b19a-12f49e647200
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-22T05:52:27+00:00'
            elementCondition: null
            fieldUid: 8c2ae0e0-bafc-45d7-ac4b-2de4bd0cabec # Text Area
            handle: testimonialText
            includeInCards: false
            instructions: null
            label: 'Testimonial Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9245fd09-e50e-43a7-9c86-47adeabafdd6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-22T05:52:27+00:00'
            elementCondition: null
            fieldUid: 7aea93d0-d819-4905-8279-efcfd692ad42 # Text
            handle: employeeName
            includeInCards: false
            instructions: null
            label: 'Employee Name'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93403303-db85-493c-86db-3b9541ba2970
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 66dc11b9-261b-4b65-89d5-799ca51042d9
        userCondition: null
handle: employeeText
hasTitleField: false
icon: input-text
name: 'Employee Text'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
