color: emerald
fieldLayouts:
  a97bf110-6799-4c04-8426-0853163a9491:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-22T05:47:49+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 00dfac9a-3943-48a7-94b3-a9670f895ab7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-22T05:51:23+00:00'
            elementCondition: null
            fieldUid: d54816d2-a954-46ab-b48e-ee1b79a75db5 # Youtube Video
            handle: video
            includeInCards: false
            instructions: 'Please entry Youtube or Vimeo video URL'
            label: Video
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 449e8455-db60-4798-93ca-06e0c1fdf4ae
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-22T05:51:23+00:00'
            elementCondition: null
            fieldUid: 64b3113c-4c07-47b2-bed6-94149314dc80 # RTE - Text Only
            handle: videoText
            includeInCards: false
            instructions: null
            label: 'Video Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93475d6f-f3d0-4019-9341-623626b58d4e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8c5e4b6d-5e30-4f9a-a2bf-b41b9b6b8562
        userCondition: null
handle: employeeVideo
hasTitleField: false
icon: user
name: 'Employee Video'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
