color: null
fieldLayouts:
  2e52717b-b45c-4ba8-8faf-5725339ac2c3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-23T08:49:34+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f0ad1ca9-5eed-462b-849d-490fc36754cd
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-23T08:52:27+00:00'
            elementCondition: null
            fieldUid: 7aea93d0-d819-4905-8279-efcfd692ad42 # Text
            handle: subtitle
            includeInCards: false
            instructions: null
            label: Subtitle
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 263fb6c2-8b1d-458c-bf31-6c63acc18e3f
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-23T08:52:27+00:00'
            elementCondition: null
            fieldUid: fa17e174-c530-4f36-8305-39230e6384a1 # RTE - Paragraph
            handle: text
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3bfc7e47-7558-4814-9502-f5eeeb386d2a
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-23T08:52:27+00:00'
            elementCondition: null
            fieldUid: b3e9cdaa-43c9-498a-bbab-42cad816e875 # Button
            handle: bookButton
            includeInCards: false
            instructions: null
            label: 'Book Button'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4dc7f91d-f7d6-498f-a8a1-97ef413a1e6c
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-23T08:52:27+00:00'
            elementCondition: null
            fieldUid: 9a317b51-ae0e-4d3a-ba59-4ec92537f560 # Extensions Table
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b6531270-5e4b-4603-8d49-100199776367
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 469c9fc8-ade4-446c-9a7c-0a988f912efb
        userCondition: null
handle: extensionPricing
hasTitleField: true
icon: ''
name: 'Extension Pricing'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
