color: null
fieldLayouts:
  77d43095-53c9-4c10-a4ed-c87beef97a5c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-23T08:29:44+00:00'
            elementCondition: null
            fieldUid: 84283218-957b-4c9d-a1d9-ed73c435cde8 # Image
            handle: brandLogo
            includeInCards: false
            instructions: null
            label: 'Brand Logo'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 39803caf-9637-4e6b-ab27-a9a40bd92be0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-23T08:29:44+00:00'
            elementCondition: null
            fieldUid: 120ae2f3-6207-4501-92e4-c3107dc65cb5 # Pricing for 3 Lengths
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 79c68221-4bd5-4707-b230-a67691401e10
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6773b01f-386c-4b16-8833-86b0fe380cb9
        userCondition: null
handle: extensionsPricingFor3
hasTitleField: false
icon: ''
name: 'Extensions Pricing for 3 lengths'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
