color: null
fieldLayouts:
  54ca2636-7dba-4b23-9b71-92e0e57ad49f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-23T08:31:17+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Service Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e68330c5-102f-48a0-b76d-bf62d7389e54
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-23T08:34:03+00:00'
            elementCondition: null
            fieldUid: 84283218-957b-4c9d-a1d9-ed73c435cde8 # Image
            handle: serviceImage
            includeInCards: false
            instructions: null
            label: 'Service Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b19a90d-37c8-4f00-b524-953b3a99bb38
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-23T08:34:03+00:00'
            elementCondition: null
            fieldUid: 64b3113c-4c07-47b2-bed6-94149314dc80 # RTE - Text Only
            handle: serviceDescription
            includeInCards: false
            instructions: null
            label: 'Service Description'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a08168d-d80e-4d87-a527-865a38a4df05
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-23T08:34:03+00:00'
            elementCondition: null
            fieldUid: 91fc3931-66af-4a46-90cf-b0ede459b66b # Local Salons
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 22294cfe-60b4-4e73-ba6d-d812e73a766b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9896318c-ee33-4cd3-b715-4d41488b2c33
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-23T08:34:42+00:00'
            elementCondition: null
            fieldUid: 9a317b51-ae0e-4d3a-ba59-4ec92537f560 # Extensions Table
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28d5a4e1-938c-44f1-80cf-4622e2f36c1e
            userCondition: null
            warning: null
            width: 100
        name: Extensions
        uid: 1b4dd4ea-03bb-4dea-b5b6-0782d41a1c49
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-23T08:34:42+00:00'
            elementCondition: null
            fieldUid: 067dc454-76f0-47fe-8a39-6380da7fc55e # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9850226f-d07e-440a-bc83-d739e6bdabab
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 4e3bd557-a156-4647-9764-dfa5e11bc9df
        userCondition: null
handle: extensions
hasTitleField: true
icon: ''
name: Extensions
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
