color: orange
fieldLayouts:
  2087f2c4-b622-4736-a7f1-858255a88b71:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-19T06:27:47+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Section Heading'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 559742bc-0478-42aa-8c21-99153290fe63
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-18T05:14:45+00:00'
            elementCondition: null
            fieldUid: 84283218-957b-4c9d-a1d9-ed73c435cde8 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d4e4e052-1851-448e-9b5f-087722797b12
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-19T05:45:49+00:00'
            elementCondition: null
            fieldUid: b7b36318-f071-4097-8730-a77ac7b5fe96 # RTE - Simple Text
            handle: imageOverlappingText
            includeInCards: false
            instructions: null
            label: 'Image Overlapping Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d60484c-a6f8-4682-ba7f-2bf799705be7
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-18T05:14:45+00:00'
            elementCondition: null
            fieldUid: b3e9cdaa-43c9-498a-bbab-42cad816e875 # Button
            handle: cta1
            includeInCards: false
            instructions: null
            label: 'CTA 1'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1af580bc-f85e-4105-9d22-841017833ece
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-18T05:14:45+00:00'
            elementCondition: null
            fieldUid: b3e9cdaa-43c9-498a-bbab-42cad816e875 # Button
            handle: cta2
            includeInCards: false
            instructions: null
            label: 'CTA 2'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa34f072-23a8-4a30-9776-5204b1c2ce15
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-19T06:12:30+00:00'
            elementCondition: null
            fieldUid: 2c098971-cf38-4baf-99ba-c248dd975d79 # Features
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 46b33b2c-72c2-450c-b500-cfaf39b8316e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f0c94ef3-efa4-4fce-966d-1c4df428f0cf
        userCondition: null
handle: featuresWCtasSection
hasTitleField: true
icon: sidebar
name: 'Features w/ CTAs Section'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
