color: null
fieldLayouts:
  07038231-81a8-4578-af1b-d2c4b705c6c5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-19T06:12:10+00:00'
            elementCondition: null
            fieldUid: 27b29006-47a2-40b1-a7c1-7f0db71cc8a2 # Icon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c354dfb3-e67d-43ce-be8e-8041d082d9b9
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-19T06:12:10+00:00'
            elementCondition: null
            fieldUid: 8c2ae0e0-bafc-45d7-ac4b-2de4bd0cabec # Text Area
            handle: heading
            includeInCards: false
            instructions: null
            label: Heading
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 13cb958d-f95a-4d65-8faf-97620eb799c8
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-19T06:12:10+00:00'
            elementCondition: null
            fieldUid: 8c2ae0e0-bafc-45d7-ac4b-2de4bd0cabec # Text Area
            handle: summary
            includeInCards: false
            instructions: null
            label: Summary
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a6c5181-7aad-4724-bf72-ab5b219de040
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e9ec2121-15f2-4dfe-acdb-2260628651b9
        userCondition: null
handle: features
hasTitleField: false
icon: compact-disc
name: Features
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
