color: null
fieldLayouts:
  9c558655-0d6c-4aa6-8526-cacaa0e6e5e6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-16T11:30:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8ac9c8e7-dd9e-47f0-b357-e85a9e80e79a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-16T11:31:39+00:00'
            elementCondition: null
            fieldUid: 96afe1ed-1049-4810-88fc-7c06133c2e03 # RTE - Full
            handle: pageContent
            includeInCards: false
            instructions: null
            label: 'Page Content'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e218535-13d4-47eb-8313-766f5643cf8f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9f55e453-29f0-4843-84dd-63f009c4caba
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-10-16T11:31:39+00:00'
            elementCondition: null
            fieldUid: 067dc454-76f0-47fe-8a39-6380da7fc55e # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 32934a0d-ac75-4b08-8280-e028be8977f5
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 18f8de69-430f-445a-bf7c-e4f7dd6f4b98
        userCondition: null
handle: generalPages
hasTitleField: true
icon: ''
name: 'General Pages'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
