color: null
fieldLayouts:
  cc571c50-9d27-4503-a260-177bd62b6c0b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-08T13:36:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e1ff899a-6c53-4a34-babd-9a7428b506c2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9cccb05f-85e8-4e71-b342-31d0f86e0385
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-08T13:37:27+00:00'
            elementCondition: null
            fieldUid: 067dc454-76f0-47fe-8a39-6380da7fc55e # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 65d7366e-d69e-4c05-9ffb-495730b302f8
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: fc0ff4de-988b-4205-b217-12e2c95b76b6
        userCondition: null
handle: home
hasTitleField: true
icon: ''
name: Home
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
