color: null
fieldLayouts:
  cc571c50-9d27-4503-a260-177bd62b6c0b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-08T13:36:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e1ff899a-6c53-4a34-babd-9a7428b506c2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-21T06:51:16+00:00'
            elementCondition: null
            fieldUid: 84283218-957b-4c9d-a1d9-ed73c435cde8 # Image
            handle: heroImage
            includeInCards: false
            instructions: null
            label: 'Hero Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b77b08eb-bcab-4de1-af36-ff275946e21e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-21T07:02:15+00:00'
            elementCondition: null
            fieldUid: 64b3113c-4c07-47b2-bed6-94149314dc80 # RTE - Text Only
            handle: heroText
            includeInCards: false
            instructions: null
            label: 'Hero Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7aa6182-04f7-4d35-a509-0198412a2c9b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-21T07:02:15+00:00'
            elementCondition: null
            fieldUid: d54816d2-a954-46ab-b48e-ee1b79a75db5 # Youtube Video
            handle: null
            includeInCards: false
            instructions: 'It video will pop-up on click the pay button.'
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e4eafc5-206e-4711-9579-513cb0865ea1
            userCondition: null
            warning: null
            width: 100
        name: Hero
        uid: 9cccb05f-85e8-4e71-b342-31d0f86e0385
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-21T07:35:31+00:00'
            elementCondition: null
            fieldUid: 8c2ae0e0-bafc-45d7-ac4b-2de4bd0cabec # Text Area
            handle: highlightedHeading
            includeInCards: false
            instructions: null
            label: 'Highlighted Heading Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 276b3fbf-89c2-4447-8ebd-908005f275e0
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-21T07:35:31+00:00'
            elementCondition: null
            fieldUid: 8c2ae0e0-bafc-45d7-ac4b-2de4bd0cabec # Text Area
            handle: greyHeading
            includeInCards: false
            instructions: null
            label: 'Grey Heading Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c2da70f-e2f9-43e6-986b-c59317654138
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-21T07:35:31+00:00'
            elementCondition: null
            fieldUid: 7aea93d0-d819-4905-8279-efcfd692ad42 # Text
            handle: singleLineText
            includeInCards: false
            instructions: null
            label: 'Single Line Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d055799-28f0-4d8e-8fc8-d6709a5e30d3
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-21T07:35:31+00:00'
            elementCondition: null
            fieldUid: aa88dbbd-c68f-44c0-bb5f-efd07e8cb367 # CTA
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63cd0db7-0ed4-447c-b4e7-3a20fd3203dc
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-21T11:39:56+00:00'
            elementCondition: null
            fieldUid: 8c2ae0e0-bafc-45d7-ac4b-2de4bd0cabec # Text Area
            handle: careerHeading
            includeInCards: false
            instructions: null
            label: 'Career Heading'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c2f2a1f-65de-4832-9909-c4648528cdb8
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-21T11:39:56+00:00'
            elementCondition: null
            fieldUid: 8c2ae0e0-bafc-45d7-ac4b-2de4bd0cabec # Text Area
            handle: careerSubheading
            includeInCards: false
            instructions: null
            label: 'Career Subheading'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c532405-4e75-42f3-8673-700e4002de87
            userCondition: null
            warning: null
            width: 50
        name: 'Halo Career'
        uid: a0f0a532-c200-4c44-8e5a-386fb8a3b862
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-21T07:43:35+00:00'
            elementCondition: null
            fieldUid: 8c2ae0e0-bafc-45d7-ac4b-2de4bd0cabec # Text Area
            handle: heading
            includeInCards: false
            instructions: null
            label: Heading
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 69c6cf40-e043-466f-b367-bba67da1c221
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-21T07:43:35+00:00'
            elementCondition: null
            fieldUid: aa88dbbd-c68f-44c0-bb5f-efd07e8cb367 # CTA
            handle: cta2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4528452d-3b45-4322-ba99-7f47497f6b5e
            userCondition: null
            warning: null
            width: 100
        name: 'Join Us'
        uid: 2eba7f8f-0444-4b02-bd76-2231e3695934
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-21T07:41:37+00:00'
            elementCondition: null
            fieldUid: 71388431-55ea-4c3f-a6a8-6b7a3bdd51b6 # Video Testimonials
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 941a361f-4bd4-40fc-92fc-0de3810ca674
            userCondition: null
            warning: null
            width: 100
        name: 'Video Testimonials'
        uid: 58fcc293-15ab-4ed9-b822-3fac529a5335
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-08T13:37:27+00:00'
            elementCondition: null
            fieldUid: 067dc454-76f0-47fe-8a39-6380da7fc55e # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 65d7366e-d69e-4c05-9ffb-495730b302f8
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: fc0ff4de-988b-4205-b217-12e2c95b76b6
        userCondition: null
handle: home
hasTitleField: true
icon: ''
name: Home
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
