color: cyan
fieldLayouts:
  82020b21-f4c7-4e44-8454-58028e127bfa:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-20T06:39:10+00:00'
            elementCondition: null
            fieldUid: 6237cfb7-a277-4a24-83f1-baadcffccf14 # Styled Cards
            handle: imageCards
            includeInCards: false
            instructions: null
            label: 'Image Cards'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc8204c1-166a-4d61-8769-d594c197eaad
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 05837a1b-96ff-459d-ba9e-bf4658a65285
        userCondition: null
handle: imageCardsSection
hasTitleField: false
icon: images
name: 'Image Cards Section'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
