color: cyan
fieldLayouts:
  82020b21-f4c7-4e44-8454-58028e127bfa:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-18T06:44:13+00:00'
            elementCondition: null
            fieldUid: 1290b18c-3072-4138-8fd2-b4808503a83f # Text w/ Image Cards
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad8fc380-05ac-4c45-8853-0ed8aac23a37
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 05837a1b-96ff-459d-ba9e-bf4658a65285
        userCondition: null
handle: imageCardsSection
hasTitleField: false
icon: images
name: 'Image Cards Section'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
