color: null
fieldLayouts:
  230ced69-a554-44d1-9c36-f091c9f73c41:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-21T04:34:47+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'City Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f3a312df-1a06-48f3-9a31-f07401ca51a3
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-21T06:45:25+00:00'
            elementCondition: null
            fieldUid: 5b40a23e-fc7b-48ed-b092-746f8700aa48 # Opening Month
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6423dcbd-7b0f-4c70-8170-8ed6f8b66f70
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-21T04:49:42+00:00'
            elementCondition: null
            fieldUid: 2f4521a5-bf9c-4655-bd15-483fa28c005f # Year
            handle: openingYear
            includeInCards: false
            instructions: null
            label: 'Opening Year'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 13b2fc7f-1afa-46fc-9177-e53f51fc9547
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-21T04:49:42+00:00'
            elementCondition: null
            fieldUid: 7f82abc5-4a85-431f-8ffa-c9d3452c3c4e # Phase
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e8471ac0-016f-4dca-a872-dd111d632bc4
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-21T04:53:34+00:00'
            elementCondition: null
            fieldUid: 84283218-957b-4c9d-a1d9-ed73c435cde8 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7723db7a-beb2-48db-9e49-965b1da9bb51
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-21T11:17:32+00:00'
            elementCondition: null
            fieldUid: 84283218-957b-4c9d-a1d9-ed73c435cde8 # Image
            handle: logo
            includeInCards: false
            instructions: null
            label: 'Desktop Logo'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54821e8c-28df-4c96-9f5c-9ae267249017
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-25T11:24:17+00:00'
            elementCondition: null
            fieldUid: 84283218-957b-4c9d-a1d9-ed73c435cde8 # Image
            handle: logoMobile
            includeInCards: false
            instructions: null
            label: 'Logo Mobile'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ef7bb60-9d2c-4694-bdc4-776717e22eb9
            userCondition: null
            warning: null
            width: 50
        name: 'General Detail'
        uid: 45091198-6547-4036-aa85-4d1135c1e130
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-17T12:32:42+00:00'
            elementCondition: null
            fieldUid: 84283218-957b-4c9d-a1d9-ed73c435cde8 # Image
            handle: heroImage
            includeInCards: false
            instructions: null
            label: 'Hero Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63bd51d7-4918-45c1-a612-a423c636fb03
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-17T12:32:42+00:00'
            elementCondition: null
            fieldUid: cf0e65ca-30ab-4935-927a-fcd42d5112b6 # Video
            handle: heroVideo
            includeInCards: false
            instructions: null
            label: 'Hero Video'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 25c679e4-f93d-4d55-8504-5a9f77bfc67a
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-17T12:32:42+00:00'
            elementCondition: null
            fieldUid: 64b3113c-4c07-47b2-bed6-94149314dc80 # RTE - Text Only
            handle: heroText
            includeInCards: false
            instructions: null
            label: 'Hero Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb500f79-97b6-4662-81ce-f20e828c2371
            userCondition: null
            warning: null
            width: 100
        name: 'Page Hero'
        uid: 142cd355-dee2-4002-b617-3bd8ee7f0751
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-18T06:45:15+00:00'
            elementCondition: null
            fieldUid: 32ebdec2-6e1e-46de-8c50-f18ddfbde228 # Local Salon Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df6dd13c-6040-4e10-9dfa-316cbb8f52a1
            userCondition: null
            warning: null
            width: 100
        name: 'Page Content'
        uid: 5c196bfa-7396-4cec-bb3a-484885441334
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-18T06:45:15+00:00'
            elementCondition: null
            fieldUid: 067dc454-76f0-47fe-8a39-6380da7fc55e # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f6882cbc-fdd1-4c2d-9942-656dc1ebb4dd
            userCondition: null
            warning: null
            width: 100
        name: 'Page SEO'
        uid: 74b6a757-f1f7-4e01-8755-4419f5d03699
        userCondition: null
handle: localSalon
hasTitleField: true
icon: ''
name: 'Local Salon'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
