color: null
fieldLayouts:
  7d3bdc7b-f8f7-4317-bd23-1ccf2ea338bf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-22T05:56:47+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4a30e28b-7417-4a17-bd3b-cd504cf9d58d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-22T05:59:03+00:00'
            elementCondition: null
            fieldUid: 84283218-957b-4c9d-a1d9-ed73c435cde8 # Image
            handle: heroImage
            includeInCards: false
            instructions: null
            label: 'Hero Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 67ed69ef-ed4d-4bdf-b8ec-72d08bf48f4c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-22T05:59:03+00:00'
            elementCondition: null
            fieldUid: 64b3113c-4c07-47b2-bed6-94149314dc80 # RTE - Text Only
            handle: heroText
            includeInCards: false
            instructions: null
            label: 'Hero Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 957e3c86-b5b1-4adf-831b-a365806ec564
            userCondition: null
            warning: null
            width: 100
        name: 'Hero Section'
        uid: 72937542-2b6c-4a38-a1ef-44e82de5d02a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-22T06:12:22+00:00'
            elementCondition: null
            fieldUid: cfe1f9f6-7ba4-4eec-af4d-d8fcd8687f6d # Text / Image Cards
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93a0b992-0d4f-4a96-a095-01e738ba272c
            userCondition: null
            warning: null
            width: 100
        name: 'Text / Image Cards'
        uid: 413d462b-41e6-4fdd-a929-4572c81a7bc0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-10-22T11:21:42+00:00'
            elementCondition: null
            fieldUid: b7b36318-f071-4097-8730-a77ac7b5fe96 # RTE - Simple Text
            handle: mainText
            includeInCards: false
            instructions: null
            label: 'Main Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f1b33c81-3aed-4bf3-9689-968fd0e51247
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-22T06:20:54+00:00'
            elementCondition: null
            fieldUid: 6d9a1d3c-2949-4ee9-8f74-78152e0ad6f6 # Process
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93d131d7-9114-4a89-8581-f665a4317a8d
            userCondition: null
            warning: null
            width: 100
        name: 'Recruitement Process'
        uid: 8b9cb40f-ecbf-4eec-b992-6c70935fc87a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-22T13:18:06+00:00'
            elementCondition: null
            fieldUid: 812c0fbf-668a-47f6-b48f-433f3e4d5550 # Image Cards
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 78f66b43-5c30-44de-94b0-b3753ce6a25f
            userCondition: null
            warning: null
            width: 100
        name: 'Image Cards'
        uid: 9b387b08-b2d1-4489-a083-c96c51fe0dd4
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-22T06:12:22+00:00'
            elementCondition: null
            fieldUid: 067dc454-76f0-47fe-8a39-6380da7fc55e # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 02b9d761-00b2-4706-b656-92bf1b9e3689
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: b14c01bb-d40d-4a3c-848f-af7aba59a589
        userCondition: null
handle: ourCulture
hasTitleField: true
icon: ''
name: 'Our Culture Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
