color: null
fieldLayouts:
  a156a354-193e-4ef5-b29e-c18f8f7944ba:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-22T05:38:04+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ea0ddaec-3047-4304-8973-489bc7eb70f1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-22T11:46:26+00:00'
            elementCondition: null
            fieldUid: 7aea93d0-d819-4905-8279-efcfd692ad42 # Text
            handle: introHeading
            includeInCards: false
            instructions: null
            label: 'Intro Heading'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 19f1dda7-4192-4db6-828e-4cf90cc28835
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-22T11:46:26+00:00'
            elementCondition: null
            fieldUid: 8c2ae0e0-bafc-45d7-ac4b-2de4bd0cabec # Text Area
            handle: introText
            includeInCards: false
            instructions: null
            label: 'Intro Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cddc0115-8249-491d-a261-d633c79f0fd0
            userCondition: null
            warning: null
            width: 100
        name: Introduction
        uid: ba0146a8-496c-40ff-beec-ac1bddcd8342
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-22T05:53:17+00:00'
            elementCondition: null
            fieldUid: f1bd2935-9135-4dfd-aec4-e7459ca70d1d # Employee Speaks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a4359870-f437-48de-b2dc-767a385fec3e
            userCondition: null
            warning: null
            width: 100
        name: 'Employee Speaks'
        uid: 48e31218-5e87-4cfc-afe4-c56798b61d1e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-22T05:59:24+00:00'
            elementCondition: null
            fieldUid: 067dc454-76f0-47fe-8a39-6380da7fc55e # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 419db6f0-bd3f-4393-8fad-f5dee34284c7
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 2c37d5a1-5169-4d8b-a301-e605081eda44
        userCondition: null
handle: ourPeople
hasTitleField: false
icon: ''
name: 'Our People'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
