color: null
fieldLayouts:
  a156a354-193e-4ef5-b29e-c18f8f7944ba:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-22T08:42:13+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7ee7d1f7-d8b9-487d-b61e-1e47ed0a543f
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-26T04:52:14+00:00'
            elementCondition: null
            fieldUid: 84283218-957b-4c9d-a1d9-ed73c435cde8 # Image
            handle: logo
            includeInCards: false
            instructions: null
            label: 'Header Logo'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d1e1cf60-a517-4e4e-9c2c-2d844591860b
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-10-14T12:24:02+00:00'
            elementCondition: null
            fieldUid: 64b3113c-4c07-47b2-bed6-94149314dc80 # RTE - Text Only
            handle: introText
            includeInCards: false
            instructions: null
            label: 'Intro Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad4497e6-f81c-4017-a3af-1061d3053098
            userCondition: null
            warning: null
            width: 100
        name: Introduction
        uid: ba0146a8-496c-40ff-beec-ac1bddcd8342
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-22T05:53:17+00:00'
            elementCondition: null
            fieldUid: f1bd2935-9135-4dfd-aec4-e7459ca70d1d # Employee Speaks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a4359870-f437-48de-b2dc-767a385fec3e
            userCondition: null
            warning: null
            width: 100
        name: 'Employee Speaks'
        uid: 48e31218-5e87-4cfc-afe4-c56798b61d1e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-22T05:59:24+00:00'
            elementCondition: null
            fieldUid: 067dc454-76f0-47fe-8a39-6380da7fc55e # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 419db6f0-bd3f-4393-8fad-f5dee34284c7
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 2c37d5a1-5169-4d8b-a301-e605081eda44
        userCondition: null
handle: ourPeople
hasTitleField: true
icon: ''
name: 'Our People Page'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
