color: blue
fieldLayouts:
  9b675a64-bdc5-4111-89fc-4d4ba22f4b60:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-18T05:46:20+00:00'
            elementCondition: null
            fieldUid: 68ba543b-e8a1-466a-9338-af5cc2d458dd # Images
            handle: photoCollage
            includeInCards: false
            instructions: null
            label: 'Photo Collage'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3e0c45d-30e8-4a1a-84b7-1a8924ea7d94
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-18T05:46:20+00:00'
            elementCondition: null
            fieldUid: b7b36318-f071-4097-8730-a77ac7b5fe96 # RTE - Simple Text
            handle: photoCollageText
            includeInCards: false
            instructions: null
            label: 'Photo Collage Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e44ac41c-a9d1-484c-91bf-0d1ee33917c0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: dba9a3da-b9f8-42ae-8ef4-f7caf9044556
        userCondition: null
handle: photoCollage
hasTitleField: false
icon: photo-film
name: 'Photo Collage'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
