color: null
fieldLayouts:
  4f51b758-9653-4013-8932-8ffe763bd377:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-23T08:39:11+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5938c1b4-0acd-453a-8b2a-dd767190df0d
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-23T09:24:17+00:00'
            elementCondition: null
            fieldUid: 7aea93d0-d819-4905-8279-efcfd692ad42 # Text
            handle: subtitle
            includeInCards: false
            instructions: null
            label: Subtitle
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 97ea1afe-9c83-4d9b-96e4-a0ff998bfe11
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-23T08:44:36+00:00'
            elementCondition: null
            fieldUid: 84283218-957b-4c9d-a1d9-ed73c435cde8 # Image
            handle: heroImage
            includeInCards: false
            instructions: null
            label: 'Hero Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 87e79c95-9509-4194-9e52-2284ace176d7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-23T08:44:36+00:00'
            elementCondition: null
            fieldUid: 64b3113c-4c07-47b2-bed6-94149314dc80 # RTE - Text Only
            handle: heroText
            includeInCards: false
            instructions: null
            label: 'Hero Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 78b09391-516b-4871-9da8-7eba7fb4e1fc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-23T09:46:11+00:00'
            elementCondition: null
            fieldUid: b3e9cdaa-43c9-498a-bbab-42cad816e875 # Button
            handle: heroCta
            includeInCards: false
            instructions: null
            label: 'Hero CTA'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f39e286f-1db6-4665-8f69-705e53c3444c
            userCondition: null
            warning: null
            width: 100
        name: Hero
        uid: 2f05a937-398f-4553-a4e9-542bb8f6df80
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-23T08:44:36+00:00'
            elementCondition: null
            fieldUid: 75cd61c4-5e05-4481-b899-fbc4d29d5770 # Pricing Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 377a4bcc-974c-4bbb-913f-a008f42fc3da
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 05142aae-5264-423c-bcef-fd59909226f0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-23T10:34:03+00:00'
            elementCondition: null
            fieldUid: 067dc454-76f0-47fe-8a39-6380da7fc55e # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d3ceaa33-b838-4e11-906d-b17bc8c207e6
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: b99ba612-ea37-45d5-b3f9-a299854a1c7b
        userCondition: null
handle: pricingContent
hasTitleField: true
icon: ''
name: 'Pricing Content'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
