color: null
fieldLayouts:
  2e815ba2-9da0-4f6a-8d1d-64980b3a5bd1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-22T06:59:33+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d379545f-afe4-49b6-b391-f92e38cbb527
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-22T07:01:38+00:00'
            elementCondition: null
            fieldUid: 7aea93d0-d819-4905-8279-efcfd692ad42 # Text
            handle: heading
            includeInCards: false
            instructions: null
            label: Heading
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 994a9233-901d-4930-9e6c-c441ade04ee6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-22T07:01:38+00:00'
            elementCondition: null
            fieldUid: 8c2ae0e0-bafc-45d7-ac4b-2de4bd0cabec # Text Area
            handle: text
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0fcb9dde-532d-467d-b57e-a1e2a201456f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-22T07:01:38+00:00'
            elementCondition: null
            fieldUid: 84283218-957b-4c9d-a1d9-ed73c435cde8 # Image
            handle: hoverImage
            includeInCards: false
            instructions: null
            label: 'Hover Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cfc7b634-4c51-4c74-ad21-73cea26cf1c7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ce97989f-56bd-4548-9aeb-11a738b8395d
        userCondition: null
handle: processStep
hasTitleField: false
icon: ''
name: 'Process Step'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
