color: null
fieldLayouts:
  1c75a427-7bf1-4055-86d1-6636f9a18b3c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-22T11:03:27+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ef248818-13c7-466c-9058-4b445cf59ca0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-22T11:05:13+00:00'
            elementCondition: null
            fieldUid: b7b36318-f071-4097-8730-a77ac7b5fe96 # RTE - Simple Text
            handle: text
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ac5a781-5a85-4377-ac76-00b844d6ca8e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7bef3188-e578-42cb-8bbd-b51c1fdeee3e
        userCondition: null
handle: processText
hasTitleField: false
icon: ''
name: 'Process Text'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
