color: null
fieldLayouts:
  e325daec-a5f4-44b7-9186-2db863b09b87:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-22T06:42:40+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6c9c3ad1-c426-46c1-ab99-487fd03e2a1e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-22T06:55:34+00:00'
            elementCondition: null
            fieldUid: 7aea93d0-d819-4905-8279-efcfd692ad42 # Text
            handle: tabHeading
            includeInCards: false
            instructions: null
            label: 'Tab Heading'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 515003e2-3007-42aa-874c-2e92c267fae8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-22T06:55:34+00:00'
            elementCondition: null
            fieldUid: 64b3113c-4c07-47b2-bed6-94149314dc80 # RTE - Text Only
            handle: tabContent
            includeInCards: false
            instructions: null
            label: 'Tab Content'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 787c7c4d-7936-454e-8e65-6d1aeb9a07cf
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a7ba994c-1ec7-410f-abfa-40147b0035f9
        userCondition: null
handle: recruitmentProcess
hasTitleField: false
icon: ''
name: 'Recruitment Process'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
