color: null
fieldLayouts:
  84d61265-c07b-4a00-b8b7-a6d32acf5bab:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-17T12:11:20+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Service Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d4dba9ac-e3aa-477e-831f-522cbeb37b56
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-17T12:13:31+00:00'
            elementCondition: null
            fieldUid: 84283218-957b-4c9d-a1d9-ed73c435cde8 # Image
            handle: serviceImage
            includeInCards: false
            instructions: null
            label: 'Service Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f7970b77-ac60-4d46-82ce-782ed86a3ab6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-17T12:13:31+00:00'
            elementCondition: null
            fieldUid: 64b3113c-4c07-47b2-bed6-94149314dc80 # RTE - Text Only
            handle: null
            includeInCards: false
            instructions: null
            label: 'Service Description'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dbf2a88c-c5da-4d87-b475-f79e11c30a85
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ae9245eb-3e30-4e15-be0b-98d5c83cb800
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-17T12:13:31+00:00'
            elementCondition: null
            fieldUid: 067dc454-76f0-47fe-8a39-6380da7fc55e # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b3f50910-294a-4d07-9ef1-ec836dac5e00
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 841afebc-ad29-43b9-aa6e-3559bdb3df6b
        userCondition: null
handle: services
hasTitleField: true
icon: ''
name: Services
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
