color: yellow
fieldLayouts:
  9f34b7ef-c350-4355-bd89-722afbef6e81:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-18T05:17:41+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Section Heading'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 334fe93e-856f-4d20-b9e1-2cb28b799f5a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-18T05:17:41+00:00'
            elementCondition: null
            fieldUid: 875175ae-1cd7-4e52-82ea-3ba5a7a69033 # Services
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05a1ae50-f29e-4b18-a7f1-25722c70a7e3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6372f9ab-9a2a-4d6c-856b-2668049300e6
        userCondition: null
handle: servicesSection
hasTitleField: true
icon: bell-concierge
name: 'Services Section'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
