color: null
fieldLayouts:
  404cfdf5-06d5-4c87-b087-b25a640cd864:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-23T08:43:58+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bce05055-9b5e-4754-9f61-9d5ecf6102ba
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-23T08:48:41+00:00'
            elementCondition: null
            fieldUid: 7aea93d0-d819-4905-8279-efcfd692ad42 # Text
            handle: subtitle
            includeInCards: false
            instructions: null
            label: Subtitle
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47e33bb2-df66-411c-93d4-8f8f8162b219
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-23T10:29:47+00:00'
            elementCondition: null
            fieldUid: fa17e174-c530-4f36-8305-39230e6384a1 # RTE - Paragraph
            handle: text
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2e34fa9f-4780-4e88-8b3c-e6f4cdc0cf73
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2024-11-23T08:48:41+00:00'
            elementCondition: null
            fieldUid: 57e46740-bfbe-4ccd-a49e-a9b613807a45 # Lightswitch
            handle: greyBg
            includeInCards: false
            instructions: null
            label: 'Grey BG?'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 55fe7767-cd03-4ed8-ab4a-676c00c369ad
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-11-23T08:48:41+00:00'
            elementCondition: null
            fieldUid: 6dada193-0bf2-4eab-8249-d9965ed96f23 # Pricing
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36d38287-a72b-4524-b5f9-a44690d2c99d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-23T10:31:41+00:00'
            elementCondition: null
            fieldUid: 7aea93d0-d819-4905-8279-efcfd692ad42 # Text
            handle: cta1Text
            includeInCards: false
            instructions: null
            label: 'CTA 1 Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3084c46d-b68a-4bf6-8b9a-3b8f5f345b56
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-23T10:31:41+00:00'
            elementCondition: null
            fieldUid: b3e9cdaa-43c9-498a-bbab-42cad816e875 # Button
            handle: cta1
            includeInCards: false
            instructions: null
            label: 'CTA 1'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3cfba5d6-26d5-4e24-84b5-98fcf6ce9fd9
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-23T10:31:41+00:00'
            elementCondition: null
            fieldUid: 7aea93d0-d819-4905-8279-efcfd692ad42 # Text
            handle: cta2Text
            includeInCards: false
            instructions: null
            label: 'CTA 2 Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c02660eb-211d-4618-a298-e6e35c5f3731
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-23T10:31:41+00:00'
            elementCondition: null
            fieldUid: b3e9cdaa-43c9-498a-bbab-42cad816e875 # Button
            handle: cta2
            includeInCards: false
            instructions: null
            label: 'CTA 2'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77375614-78e4-4ea8-b4b5-12ae948582f7
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-23T10:36:49+00:00'
            elementCondition: null
            fieldUid: b3e9cdaa-43c9-498a-bbab-42cad816e875 # Button
            handle: bookLink
            includeInCards: false
            instructions: 'It will be applicable to all services'
            label: 'Book Link'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f83b2069-e1a2-498f-9241-50e3cf2dbfc0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f9d1f443-1e89-4656-bdbc-5f6a6ad72c65
        userCondition: null
handle: servicesPricing
hasTitleField: true
icon: ''
name: 'Services Pricing '
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
