color: null
fieldLayouts:
  b9194e9f-f980-43b4-9e1d-3b2bbc8c662a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-21T07:27:02+00:00'
            elementCondition: null
            fieldUid: 84283218-957b-4c9d-a1d9-ed73c435cde8 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: 'Header Logo'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 39511ba1-6eb6-4912-915f-fbf67eacbdd4
            userCondition: null
            warning: null
            width: 100
        name: General
        uid: 4bbcb028-888e-44e6-8a57-00626886ca20
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-21T07:27:02+00:00'
            elementCondition: null
            heading: 'Form Section'
            type: craft\fieldlayoutelements\Heading
            uid: ec3dd056-def8-4e5f-8583-615ac164ac04
            userCondition: null
          -
            dateAdded: '2024-09-21T07:27:02+00:00'
            elementCondition: null
            fieldUid: 7aea93d0-d819-4905-8279-efcfd692ad42 # Text
            handle: heading
            includeInCards: false
            instructions: null
            label: Heading
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72dee0b7-b7ce-4cf7-a0a2-2defb6615e18
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-21T07:27:02+00:00'
            elementCondition: null
            fieldUid: 64b3113c-4c07-47b2-bed6-94149314dc80 # RTE - Text Only
            handle: text
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84a6a0de-0fa0-4d3c-9407-00f144794246
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-21T07:27:02+00:00'
            elementCondition: null
            fieldUid: aa88dbbd-c68f-44c0-bb5f-efd07e8cb367 # CTA
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 79f46f60-1b17-4695-bdf5-8b5c7fde318e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-21T07:27:02+00:00'
            elementCondition: null
            fieldUid: 8c2ae0e0-bafc-45d7-ac4b-2de4bd0cabec # Text Area
            handle: formText
            includeInCards: false
            instructions: 'It will be shown above the form.'
            label: 'Form Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d835cc1-e56f-42ef-824f-1b6efc532010
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-21T07:27:02+00:00'
            elementCondition: null
            heading: 'Text Section'
            type: craft\fieldlayoutelements\Heading
            uid: b621a29c-a4fc-46b1-9bfb-4fa085dde5a9
            userCondition: null
          -
            dateAdded: '2024-09-21T07:27:02+00:00'
            elementCondition: null
            fieldUid: 64b3113c-4c07-47b2-bed6-94149314dc80 # RTE - Text Only
            handle: text2
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a5ba28e4-f590-4eb3-a4e5-096032700fa9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-21T07:27:02+00:00'
            elementCondition: null
            fieldUid: aa88dbbd-c68f-44c0-bb5f-efd07e8cb367 # CTA
            handle: cta2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: daebc77f-3ba0-4dca-aa41-f3d05e477543
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-21T07:27:02+00:00'
            elementCondition: null
            fieldUid: 4a757ae5-8a0f-4384-ab08-99d5e96e32dc # Bullet Points
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 012eb096-d585-4931-818e-44a5c3295412
            userCondition: null
            warning: null
            width: 100
        name: 'Work with Halo'
        uid: f546d70d-bc48-4575-8360-c74763ef8154
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-10-03T06:25:51+00:00'
            elementCondition: null
            fieldUid: aa88dbbd-c68f-44c0-bb5f-efd07e8cb367 # CTA
            handle: applyButton
            includeInCards: false
            instructions: null
            label: 'Apply Button'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 314b70af-127b-46eb-9abb-a98b4cc910e0
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-19T11:13:27+00:00'
            elementCondition: null
            fieldUid: b3e9cdaa-43c9-498a-bbab-42cad816e875 # Button
            handle: bookButton
            includeInCards: false
            instructions: null
            label: 'Book Button'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e65d14a-f12d-4317-b86f-159aad8b6ce5
            userCondition: null
            warning: null
            width: 50
        name: CTAs
        uid: e6de1314-dcac-4494-8ebc-b5687e026717
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-19T05:16:25+00:00'
            elementCondition: null
            fieldUid: b7b36318-f071-4097-8730-a77ac7b5fe96 # RTE - Simple Text
            handle: notificationText
            includeInCards: false
            instructions: null
            label: 'Notification Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa4435e4-8a4f-438d-8507-2a783702da6f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-19T05:16:25+00:00'
            elementCondition: null
            fieldUid: 7aea93d0-d819-4905-8279-efcfd692ad42 # Text
            handle: ctaText
            includeInCards: false
            instructions: null
            label: 'CTA Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2b4548b-4cb3-4dc8-adcb-9a9c11556a7d
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-19T05:16:49+00:00'
            elementCondition: null
            fieldUid: b3e9cdaa-43c9-498a-bbab-42cad816e875 # Button
            handle: cta1
            includeInCards: false
            instructions: null
            label: CTA
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0156b6de-f436-4cf3-a638-889c4b4e4ae1
            userCondition: null
            warning: null
            width: 50
        name: 'Top Notification'
        uid: d54209b5-663e-4966-92b0-adc8111530b3
        userCondition: null
handle: siteGlobals
hasTitleField: false
icon: ''
name: 'Site Globals'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
