color: null
fieldLayouts:
  b9194e9f-f980-43b4-9e1d-3b2bbc8c662a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-21T07:17:32+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cd7ef261-806b-4e58-b2fe-2363b8f79e89
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-21T07:27:02+00:00'
            elementCondition: null
            fieldUid: 84283218-957b-4c9d-a1d9-ed73c435cde8 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: 'Header Logo'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 39511ba1-6eb6-4912-915f-fbf67eacbdd4
            userCondition: null
            warning: null
            width: 100
        name: General
        uid: 4bbcb028-888e-44e6-8a57-00626886ca20
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-21T07:27:02+00:00'
            elementCondition: null
            heading: 'Form Section'
            type: craft\fieldlayoutelements\Heading
            uid: ec3dd056-def8-4e5f-8583-615ac164ac04
            userCondition: null
          -
            dateAdded: '2024-09-21T07:27:02+00:00'
            elementCondition: null
            fieldUid: 7aea93d0-d819-4905-8279-efcfd692ad42 # Text
            handle: heading
            includeInCards: false
            instructions: null
            label: Heading
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72dee0b7-b7ce-4cf7-a0a2-2defb6615e18
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-21T07:27:02+00:00'
            elementCondition: null
            fieldUid: 64b3113c-4c07-47b2-bed6-94149314dc80 # RTE - Text Only
            handle: text
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84a6a0de-0fa0-4d3c-9407-00f144794246
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-21T07:27:02+00:00'
            elementCondition: null
            fieldUid: aa88dbbd-c68f-44c0-bb5f-efd07e8cb367 # CTA
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 79f46f60-1b17-4695-bdf5-8b5c7fde318e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-21T07:27:02+00:00'
            elementCondition: null
            fieldUid: 8c2ae0e0-bafc-45d7-ac4b-2de4bd0cabec # Text Area
            handle: formText
            includeInCards: false
            instructions: 'It will be shown above the form.'
            label: 'Form Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d835cc1-e56f-42ef-824f-1b6efc532010
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-21T07:27:02+00:00'
            elementCondition: null
            heading: 'Text Section'
            type: craft\fieldlayoutelements\Heading
            uid: b621a29c-a4fc-46b1-9bfb-4fa085dde5a9
            userCondition: null
          -
            dateAdded: '2024-09-21T07:27:02+00:00'
            elementCondition: null
            fieldUid: 64b3113c-4c07-47b2-bed6-94149314dc80 # RTE - Text Only
            handle: text2
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a5ba28e4-f590-4eb3-a4e5-096032700fa9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-21T07:27:02+00:00'
            elementCondition: null
            fieldUid: aa88dbbd-c68f-44c0-bb5f-efd07e8cb367 # CTA
            handle: cta2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: daebc77f-3ba0-4dca-aa41-f3d05e477543
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-21T07:27:02+00:00'
            elementCondition: null
            fieldUid: 4a757ae5-8a0f-4384-ab08-99d5e96e32dc # Bullet Points
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 012eb096-d585-4931-818e-44a5c3295412
            userCondition: null
            warning: null
            width: 100
        name: 'Work with Halo'
        uid: f546d70d-bc48-4575-8360-c74763ef8154
        userCondition: null
handle: siteGlobals
hasTitleField: false
icon: ''
name: 'Site Globals'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
