color: null
fieldLayouts:
  1750e31c-3d78-4a52-b5ce-41376bc8c15b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-17T12:13:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Name
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bc8d8002-16d7-4f09-9faf-39e676fe19d6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-17T12:16:31+00:00'
            elementCondition: null
            fieldUid: 84283218-957b-4c9d-a1d9-ed73c435cde8 # Image
            handle: photo
            includeInCards: false
            instructions: null
            label: Photo
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dca82d9b-2206-4e05-a9e1-d4a447ea5a06
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-17T12:16:31+00:00'
            elementCondition: null
            fieldUid: b7b36318-f071-4097-8730-a77ac7b5fe96 # RTE - Simple Text
            handle: bio
            includeInCards: false
            instructions: null
            label: Bio
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c7fd645-bfb3-4cc6-9d95-7e78b9971ff3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-17T12:17:27+00:00'
            elementCondition: null
            fieldUid: 91fc3931-66af-4a46-90cf-b0ede459b66b # Local Salons
            handle: null
            includeInCards: false
            instructions: null
            label: 'Related to Local Salons'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee44c8d7-4271-4b05-acb5-f179dbe31028
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e11554a5-eb44-41df-a907-bddba3240969
        userCondition: null
handle: team
hasTitleField: true
icon: ''
name: Team
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
