color: green
fieldLayouts:
  51c4cf31-406a-4c76-849a-1a9aab716a80:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-22T06:08:05+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Heading
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0d0ae655-4518-4bfe-8459-b6adb31633eb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-22T06:10:31+00:00'
            elementCondition: null
            fieldUid: 8c2ae0e0-bafc-45d7-ac4b-2de4bd0cabec # Text Area
            handle: text
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 787399c0-ee4e-41aa-b414-a7e90b1a340c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-22T06:10:31+00:00'
            elementCondition: null
            fieldUid: 84283218-957b-4c9d-a1d9-ed73c435cde8 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b50b52b5-8ef7-4236-8239-25c8b4df3c21
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6626a1ac-07a4-4588-a778-7005078114ab
        userCondition: null
handle: textWImage
hasTitleField: true
icon: id-card
name: 'Text w/ Image'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
