color: sky
fieldLayouts:
  300ffb30-e965-4126-8ca8-56aaed29aab4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-22T06:09:33+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Heading
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e520671d-6438-4e0e-a116-8363ee87c54e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-22T10:59:48+00:00'
            elementCondition: null
            fieldUid: b7b36318-f071-4097-8730-a77ac7b5fe96 # RTE - Simple Text
            handle: text
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cde9a7b9-d874-42ab-8048-6598dbd58adf
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0d5d0e71-0ffd-400f-a3c3-50a5a08092df
        userCondition: null
handle: textOnly
hasTitleField: true
icon: subtitles
name: 'Text Only'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
