color: green
fieldLayouts:
  51c4cf31-406a-4c76-849a-1a9aab716a80:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-22T06:08:05+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Heading
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0d0ae655-4518-4bfe-8459-b6adb31633eb
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-18T05:50:50+00:00'
            elementCondition: null
            fieldUid: 7aea93d0-d819-4905-8279-efcfd692ad42 # Text
            handle: subheading
            includeInCards: false
            instructions: null
            label: Subheading
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2adba5f3-df98-48b3-9290-46a4c23937b1
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-10-22T10:59:24+00:00'
            elementCondition: null
            fieldUid: b7b36318-f071-4097-8730-a77ac7b5fe96 # RTE - Simple Text
            handle: text
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cba54c5b-f987-44c1-a8d8-70574119e480
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2024-09-22T06:10:31+00:00'
            elementCondition: null
            fieldUid: 84283218-957b-4c9d-a1d9-ed73c435cde8 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b50b52b5-8ef7-4236-8239-25c8b4df3c21
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 6626a1ac-07a4-4588-a778-7005078114ab
        userCondition: null
handle: textWImage
hasTitleField: true
icon: id-card
name: 'Text w/ Image'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
