color: null
fieldLayouts:
  9cd75b7a-0226-469d-a7a2-49b4c50829d3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-22T05:13:38+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7f11450c-9b5a-485b-a5aa-c2f7061468d7
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-10-14T01:50:04+00:00'
            elementCondition: null
            fieldUid: 57e46740-bfbe-4ccd-a49e-a9b613807a45 # Lightswitch
            handle: hideHeroSection
            includeInCards: false
            instructions: 'Would you like to hide hero section on the page?'
            label: 'Hide Hero Section?'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ac909291-5012-4235-b216-8222d54dab31
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-22T05:19:04+00:00'
            elementCondition: null
            fieldUid: 64b3113c-4c07-47b2-bed6-94149314dc80 # RTE - Text Only
            handle: heroText
            includeInCards: false
            instructions: null
            label: 'Hero Text'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9507c393-f0b1-44e3-a6f8-7f3e85ac6959
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-22T05:17:41+00:00'
            elementCondition: null
            fieldUid: 84283218-957b-4c9d-a1d9-ed73c435cde8 # Image
            handle: heroImage
            includeInCards: false
            instructions: null
            label: 'Hero Image'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 21a54972-7fd5-4d16-a84b-643f759aa84b
            userCondition: null
            warning: null
            width: 100
        name: 'Hero Section'
        uid: bb87d5db-575d-4434-84a5-613cafed1789
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-22T05:17:41+00:00'
            elementCondition: null
            fieldUid: c15e8516-7e75-4c32-b6a2-98d2d78dba3e # Cards
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 938c2143-5b68-4650-be61-3d1917d88a74
            userCondition: null
            warning: null
            width: 100
        name: 'Cards Section'
        uid: 4fb19df5-392c-48bd-b40c-f84b7980b903
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-22T05:17:41+00:00'
            elementCondition: null
            fieldUid: 067dc454-76f0-47fe-8a39-6380da7fc55e # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d3ebb62-623b-4aa7-9bc0-42a94b66fd78
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 5fa82f32-1611-4122-b5fd-56795cc016ed
        userCondition: null
handle: vacancies
hasTitleField: true
icon: ''
name: 'Vacancies Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
