headingLevels:
  - 2
  - 3
  - 4
  - 5
  - 6
name: 'Simple Text'
options:
  fontSize:
    options:
      - tiny
      - small
      - big
      - huge
  heading:
    options:
      -
        class: ck-heading_paragraph
        model: paragraph
        title: Paragraph
      -
        class: ck-heading_heading2
        model: heading2
        title: 'Heading 2'
        view: h2
      -
        class: ck-heading_heading3
        model: heading3
        title: 'Heading 3'
        view: h3
      -
        class: ck-heading_heading4
        model: heading4
        title: 'Heading 4'
        view: h4
      -
        class: ck-heading_heading5
        model: heading5
        title: 'Heading 5'
        view: h5
toolbar:
  - heading
  - bold
  - italic
  - underline
  - link
  - fontSize
  - fontColor
  - fontBackgroundColor
