headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
name: 'Text Only'
options:
  alignment:
    options:
      - left
      - right
      - center
      - justify
toolbar:
  - heading
  - '|'
  - bold
  - italic
  - underline
  - fontBackgroundColor
  - fontFamily
  - alignment
  - '|'
  - bulletedList
  - numberedList
  - todoList
