headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
name: 'Text Only'
options:
  alignment:
    options:
      - left
      - right
      - center
      - justify
  fontSize:
    options:
      - 9
      - 11
      - 13
      - 15
      - 17
      - 19
      - 21
      - 23
      - 25
      - 27
      - 29
toolbar:
  - heading
  - '|'
  - bold
  - italic
  - underline
  - fontBackgroundColor
  - '|'
  - fontColor
  - fontSize
  - fontFamily
  - '|'
  - alignment
  - bulletedList
  - numberedList
  - todoList
  - '|'
  - link
