headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
name: 'Text Only'
options:
  alignment:
    options:
      - left
      - right
      - center
      - justify
  fontSize:
    options:
      - tiny
      - small
      - big
      - huge
toolbar:
  - heading
  - '|'
  - bold
  - italic
  - underline
  - fontBackgroundColor
  - '|'
  - fontColor
  - fontSize
  - fontFamily
  - '|'
  - alignment
  - bulletedList
  - numberedList
  - todoList
  - '|'
  - link
