defaultPlacement: end
fieldLayouts:
  349e912c-f736-4f3c-8228-8de94100a7c2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-22T08:52:40+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 47e20ac0-d291-4fd0-a1e1-b098a94a9ee5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T08:52:40+00:00'
            elementCondition: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: verbb\navigation\fieldlayoutelements\NodeTypeElements
            uid: 109c1f82-f13b-4c5f-85e2-4fd4b22f528f
            userCondition: null
            warning: null
          -
            attribute: newWindow
            dateAdded: '2024-11-22T08:52:40+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\NewWindowField
            uid: 186cf670-463c-4241-93bc-e9e6c61e8f75
            userCondition: null
            warning: null
            width: 100
        name: Node
        uid: 99130750-c7c4-466f-9307-dc22f1c62611
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            attribute: urlSuffix
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            dateAdded: '2024-11-22T08:52:40+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\UrlSuffixField
            uid: a0e54740-4054-4644-ae36-c74f31c6acf1
            userCondition: null
            warning: null
            width: 100
          -
            attribute: classes
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            dateAdded: '2024-11-22T08:52:40+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\ClassesField
            uid: 30a2df01-5deb-4c51-b79c-edf1124bd4ef
            userCondition: null
            warning: null
            width: 100
          -
            attribute: customAttributes
            dateAdded: '2024-11-22T08:52:40+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\CustomAttributesField
            uid: 604bd5d0-c0c1-4184-824a-0560416553e8
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: a2975945-11cc-4554-8ebd-d9ad59c5ad53
        userCondition: null
handle: footerMenuColumn3
instructions: ''
maxNodes: null
name: 'Footer Menu Column 3'
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  verbb\navigation\nodetypes\CustomType:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
  verbb\navigation\nodetypes\SiteType:
    enabled: '1'
propagationMethod: all
siteSettings:
  0d1a2199-8227-4113-8872-9224a1f10ef4: # Ingleby
    enabled: false
  2d9f82e7-e967-491c-8b4c-b45ce52ab7e1: # Jobs
    enabled: true
  4fdc851f-7db3-4c90-880c-a187ac552886: # Halo Hair Group
    enabled: true
  9dde76c9-a679-4b79-a41f-2967846b76f4: # Glasgow
    enabled: false
  822d8c30-81b1-4042-b211-0f5bf17fe786: # Darlington
    enabled: false
  5241ddf9-1a26-4245-babb-b5b96cbea919: # Durham
    enabled: false
sortOrder: 5
structure:
  maxLevels: null
  uid: be01b89c-7a4b-4fcc-a4e4-fa9fa2857350
