defaultPlacement: end
fieldLayouts:
  c76c3353-8fe1-4efb-b0ad-cefcbad38758:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-22T08:52:28+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 4d3e73c7-2dbe-4f3e-9f1c-b4014935b037
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T08:52:28+00:00'
            elementCondition: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: verbb\navigation\fieldlayoutelements\NodeTypeElements
            uid: 020a201c-205e-4d74-be76-2df109dccb9d
            userCondition: null
            warning: null
          -
            attribute: newWindow
            dateAdded: '2024-11-22T08:52:28+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\NewWindowField
            uid: bf6a61f4-7135-45df-9511-e2fc043ec5c4
            userCondition: null
            warning: null
            width: 100
        name: Node
        uid: 76377b07-ad62-42d8-a0a7-64bb4966435f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            attribute: urlSuffix
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            dateAdded: '2024-11-22T08:52:28+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\UrlSuffixField
            uid: 780ef063-b792-48ff-9235-480773d9eb9f
            userCondition: null
            warning: null
            width: 100
          -
            attribute: classes
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            dateAdded: '2024-11-22T08:52:28+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\ClassesField
            uid: a6af249a-d687-4cc5-bd6a-4c69d6b4869a
            userCondition: null
            warning: null
            width: 100
          -
            attribute: customAttributes
            dateAdded: '2024-11-22T08:52:28+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\CustomAttributesField
            uid: b051a9b2-55bb-432d-8a65-3b71ff6e1103
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: 28c9511b-9a3b-4f79-a254-9b429341e172
        userCondition: null
handle: footerMenuColumn2
instructions: ''
maxNodes: null
name: 'Footer Menu Column 2'
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  verbb\navigation\nodetypes\CustomType:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
  verbb\navigation\nodetypes\SiteType:
    enabled: '1'
propagationMethod: all
siteSettings:
  0d1a2199-8227-4113-8872-9224a1f10ef4: # Ingleby
    enabled: false
  2d9f82e7-e967-491c-8b4c-b45ce52ab7e1: # Jobs
    enabled: true
  4fdc851f-7db3-4c90-880c-a187ac552886: # Halo Hair Group
    enabled: true
  9dde76c9-a679-4b79-a41f-2967846b76f4: # Glasgow
    enabled: false
  822d8c30-81b1-4042-b211-0f5bf17fe786: # Darlington
    enabled: false
  5241ddf9-1a26-4245-babb-b5b96cbea919: # Durham
    enabled: false
sortOrder: 4
structure:
  maxLevels: null
  uid: 2c3287f5-bd51-432c-b23f-784692a3f1fc
