defaultPlacement: end
fieldLayouts:
  7dbb1629-9ebf-4113-9a19-11ab137500b6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-22T08:51:43+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 1a2f8b3e-1924-49f3-994a-853430f3448f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T08:51:43+00:00'
            elementCondition: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: verbb\navigation\fieldlayoutelements\NodeTypeElements
            uid: e9faefbf-5656-4a79-96fd-8296f3530d6c
            userCondition: null
            warning: null
          -
            attribute: newWindow
            dateAdded: '2024-11-22T08:51:43+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\NewWindowField
            uid: d3c69e2c-232c-472f-ba6c-2b167b302e3b
            userCondition: null
            warning: null
            width: 100
        name: Node
        uid: 4c562ffd-9ef2-4905-b528-fa757f948c96
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            attribute: urlSuffix
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            dateAdded: '2024-11-22T08:51:43+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\UrlSuffixField
            uid: 570f6721-298f-4407-8e97-96e55a34042d
            userCondition: null
            warning: null
            width: 100
          -
            attribute: classes
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            dateAdded: '2024-11-22T08:51:43+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\ClassesField
            uid: 44b0159a-af55-4b74-80f9-f6647ff5b637
            userCondition: null
            warning: null
            width: 100
          -
            attribute: customAttributes
            dateAdded: '2024-11-22T08:51:43+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\CustomAttributesField
            uid: 6d2e2fd8-67f8-4ff6-b3a2-4e7cf23dff5c
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: aa0cf54b-acf4-4bb1-be87-dc6699ee612c
        userCondition: null
handle: footerMenuColumn1
instructions: ''
maxNodes: null
name: 'Footer Menu Column 1'
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  verbb\navigation\nodetypes\CustomType:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
  verbb\navigation\nodetypes\SiteType:
    enabled: '1'
propagationMethod: all
siteSettings:
  0d1a2199-8227-4113-8872-9224a1f10ef4: # Ingleby
    enabled: false
  2d9f82e7-e967-491c-8b4c-b45ce52ab7e1: # Jobs
    enabled: true
  4fdc851f-7db3-4c90-880c-a187ac552886: # Halo Hair Group
    enabled: true
  9dde76c9-a679-4b79-a41f-2967846b76f4: # Glasgow
    enabled: false
  822d8c30-81b1-4042-b211-0f5bf17fe786: # Darlington
    enabled: false
  5241ddf9-1a26-4245-babb-b5b96cbea919: # Durham
    enabled: false
sortOrder: 3
structure:
  maxLevels: 1
  uid: 2c2f5ad2-9e03-4d54-9974-7a8bca9a4c5b
