altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  808773e3-687b-431a-b0a9-30b15f1ba9f7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-29T10:50:36+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 3407a3ae-1f46-4ad1-8d28-61bb3e2dea3a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1df92764-3a7a-4373-bc1e-1dc31165069d
        userCondition: null
fs: uploads
handle: siteUploads
name: 'Site Uploads'
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: uploads
transformSubpath: ''
