columnSuffix: null
handle: articleNewsCategories
instructions: null
name: 'Article/News Categories'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionLabel: 'Add Categories'
  showCardsInGrid: false
  showSiteMenu: false
  sources:
    - 'section:23e5198a-09b9-4a49-848c-69fd8a0da9c1' # Article Categories
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
