columnSuffix: null
handle: bulletPoints
instructions: null
name: 'Bullet Points'
searchable: false
settings:
  addRowLabel: 'Add Bullet Point'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Text
            -
              - handle
              - text
            -
              - width
              - ''
            -
              - type
              - multiline
  defaults: null
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
