columnSuffix: null
handle: button
instructions: null
name: Button
searchable: false
settings:
  maxLength: 255
  showLabelField: true
  showTargetField: true
  typeSettings:
    __assoc__:
      -
        - entry
        -
          __assoc__:
            -
              - sources
              - '*'
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - ''
            -
              - allowAnchors
              - ''
  types:
    - entry
    - url
    - email
    - tel
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
