columnSuffix: null
handle: headingStyle
instructions: null
name: 'Heading Style'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Text
        -
          - value
          - text
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Button
        -
          - value
          - button
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
