columnSuffix: null
handle: process
instructions: null
name: Process
searchable: false
settings:
  addRowLabel: 'Add Process'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - 'Process Text'
            -
              - handle
              - processText
            -
              - width
              - ''
            -
              - type
              - multiline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
