columnSuffix: null
handle: process
instructions: null
name: Process
searchable: false
settings:
  createButtonLabel: 'Add Process'
  entryTypes:
    - 7eadd07d-e23b-4b39-8180-5438582847dd # Process Text
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: none
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
