columnSuffix: null
handle: rteFull
instructions: null
name: 'RTE - Full'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 1f1a03f8-9f09-4e72-90b2-73744ea2d88c # Full
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
