columnSuffix: null
handle: rteParagraph
instructions: null
name: 'RTE - Paragraph'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: b7405174-bb8b-4245-9f7d-abb0b0ba7331 # Paragraph
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
