columnSuffix: null
handle: services
instructions: null
name: Services
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add Services'
  showCardsInGrid: false
  showSiteMenu: false
  sources:
    - 'section:3caf09ec-53df-4e14-a191-76ad960d2171' # Services
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
