columnSuffix: null
handle: year
instructions: null
name: Year
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - '2024'
        -
          - value
          - '2024'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2025'
        -
          - value
          - '2025'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2026'
        -
          - value
          - '2026'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2027'
        -
          - value
          - '2027'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2028'
        -
          - value
          - '2028'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2029'
        -
          - value
          - '2029'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
