dateModified: 1724761042
email:
  fromEmail: bhashkar007@gmail.com
  fromName: Halo
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0ccd9cb4-cb6f-44da-b932-3dae09c2db79: 'Holding Page' # Holding Page
    4fdc851f-7db3-4c90-880c-a187ac552886: 'Halo Hair Group' # Halo Hair Group
    5a77901a-6b9c-460b-bb5c-032b263bc717: Halo # Halo
    52a63f08-5474-4cca-bc26-0d405b83ba7a: Simple # Simple
    067dc454-76f0-47fe-8a39-6380da7fc55e: SEO # SEO
    e8c8e356-5c73-4595-b2c6-b5973a67da4c: 'Holding Page' # Holding Page
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: N504S2U3EOSZSRS9T1WIHJYY
    schemaVersion: 3.0.12
system:
  edition: team
  live: true
  name: 'Halo Hair Group'
  retryDuration: null
  schemaVersion: 5.3.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
