dateModified: 1732021827
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: '*'
      tableAttributes:
        - status
        - section
        - postDate
        - authors
        - link
      type: native
    -
      key: 'single:0ccd9cb4-cb6f-44da-b932-3dae09c2db79' # Home
      type: native
    -
      key: 'single:0596fc40-de8d-419a-a76d-0d5412a5f315' # Site Globals
      type: native
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:16675a87-08c8-4f34-b9d9-1218d1eced39' # Benefit Pages
      tableAttributes:
        - status
        - postDate
        - authors
        - link
      type: native
    -
      heading: Collections
      type: heading
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:38dc9635-7a7d-484c-bffc-96bf8c1ae3e3' # Local Salons
      tableAttributes:
        - 'fieldInstance:13b2fc7f-1afa-46fc-9177-e53f51fc9547'
        - 'field:7f82abc5-4a85-431f-8ffa-c9d3452c3c4e' # Phase
        - status
        - postDate
      type: native
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:743ec001-12a3-48f1-8ebe-cb880deb1e5a' # Jobs Listing
      tableAttributes:
        - 'field:f0f5c790-85e7-436d-9f47-3e1a7966a1b1' # Job Type
        - 'field:84283218-957b-4c9d-a1d9-ed73c435cde8' # Image
        - status
        - postDate
        - authors
      type: native
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:a879f311-1328-4f30-ac91-a12a459194b1' # Pages
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - authors
        - link
      type: native
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:3777c10e-da81-4c0b-9f87-85cb8bd27b14' # Article & News
      tableAttributes:
        - status
        - postDate
        - authors
        - link
      type: native
    -
      key: 'section:3caf09ec-53df-4e14-a191-76ad960d2171' # Services
      type: native
    -
      key: 'section:925df286-518b-4bdb-a7d5-ccd461be7236' # Team
      type: native
    -
      heading: 'Job Pages'
      type: heading
    -
      key: 'single:f4a67cd2-d8bf-4d6a-9f38-4241b1f27393' # Jobs
      type: native
    -
      key: 'single:dd713845-af4e-4e60-9d0a-171d3ed41bb9' # About Us
      type: native
    -
      key: 'single:a424a048-14aa-4cdc-a80e-3cbedee60726' # Vacancies
      type: native
    -
      key: 'single:cf90e322-6859-4622-bfcb-61a01096cdc9' # Salary & Benefits
      type: native
    -
      key: 'single:b421bd1c-2476-4b2e-99f3-997e88b3f7df' # Our People
      type: native
    -
      key: 'single:e49f78c7-9b22-409e-b03e-671922e6915f' # Our Culture
      type: native
    -
      key: 'single:acb66ef8-b78e-4e0f-8040-e9fd7a84dc02' # Apply
      type: native
    -
      heading: Categories
      type: heading
    -
      key: 'section:23e5198a-09b9-4a49-848c-69fd8a0da9c1' # Article Categories
      type: native
email:
  fromEmail: $SERVD_SMTP_USERNAME
  fromName: 'Halo Hair Group'
  replyToEmail: null
  template: null
  transportSettings:
    host: $SERVD_SMTP_HOSTNAME
    password: $SERVD_SMTP_PASSWORD
    port: '2525'
    useAuthentication: '1'
    username: $SERVD_SMTP_USERNAME
  transportType: craft\mail\transportadapters\Smtp
fs:
  uploads:
    hasUrls: true
    name: Uploads
    settings:
      cdnUrlPattern: ''
      customSubfolder: ''
      makeUploadsPublic: true
      optimisePrefix: ''
      optimiseUrlPattern: ''
      projectSlug: ''
      securityKey: ''
      subfolder: local/
    type: servd\AssetStorage\AssetsPlatform\Fs
    url: 'https://halo-hair.files.svdcdn.com'
meta:
  __names__:
    0ccd9cb4-cb6f-44da-b932-3dae09c2db79: Home # Home
    0d1a2199-8227-4113-8872-9224a1f10ef4: Ingleby # Ingleby
    0d205f8c-46fe-41bf-8a0d-0f64b3877490: 'Simple Text' # Simple Text
    1dfa55bc-6378-42c8-978f-4266cf07fc70: 'Text / Image Row' # Text / Image Row
    1e7969e0-4dc9-4153-886d-a1985e4b0766: 'About Us Page' # About Us Page
    1f1a03f8-9f09-4e72-90b2-73744ea2d88c: Full # Full
    1f9056e2-e8fd-4663-8027-0bfb8882ade5: 'Text Only' # Text Only
    2a6cc5eb-ab48-4ac5-86af-300d612709dc: 'Team Members' # Team Members
    2c098971-cf38-4baf-99ba-c248dd975d79: Features # Features
    2cffa8d4-0f9f-4b73-a0b9-96d331e94d8a: 'Video Testimonial' # Video Testimonial
    2d9f82e7-e967-491c-8b4c-b45ce52ab7e1: Jobs # Jobs
    2d148f8f-2d96-4924-a878-745d3c6c6eed: 'Text w/ Image' # Text w/ Image
    2f4521a5-bf9c-4655-bd15-483fa28c005f: Year # Year
    3b0d478f-3b10-4424-9f3c-fd2c2d304e29: 'Article & News' # Article & News
    3c9ec943-aefe-47ec-81c4-89c792843eb3: 'Image Card' # Image Card
    3caf09ec-53df-4e14-a191-76ad960d2171: Services # Services
    4a757ae5-8a0f-4384-ab08-99d5e96e32dc: 'Bullet Points' # Bullet Points
    4bf1c1f4-99ad-4552-a05e-55e3c79d1f67: 'Job Benefits' # Job Benefits
    4fdc851f-7db3-4c90-880c-a187ac552886: 'Halo Hair Group' # Halo Hair Group
    5a77901a-6b9c-460b-bb5c-032b263bc717: Halo # Halo
    5b40a23e-fc7b-48ed-b092-746f8700aa48: 'Opening Month' # Opening Month
    5c1885e7-2d6a-4df5-8de7-646816d23c2a: Benefits # Benefits
    6d9a1d3c-2949-4ee9-8f74-78152e0ad6f6: Process # Process
    7aea93d0-d819-4905-8279-efcfd692ad42: Text # Text
    7eadd07d-e23b-4b39-8180-5438582847dd: 'Process Text' # Process Text
    07edd6a8-1941-47c3-8535-ccc56f465ac0: Services # Services
    7f82abc5-4a85-431f-8ffa-c9d3452c3c4e: Phase # Phase
    8bcdb7ac-055d-4548-9cda-bd6a68b501d5: 'Our Culture Page' # Our Culture Page
    8c2ae0e0-bafc-45d7-ac4b-2de4bd0cabec: 'Text Area' # Text Area
    8eb9df4d-b6b1-4331-9b12-46c97ce4b33e: 'Site Globals' # Site Globals
    8f985adb-f8ad-4b76-acd5-678c5e7c8e6d: 'Vacancies Page' # Vacancies Page
    9dde76c9-a679-4b79-a41f-2967846b76f4: Glasgow # Glasgow
    23e5198a-09b9-4a49-848c-69fd8a0da9c1: 'Article Categories' # Article Categories
    27b29006-47a2-40b1-a7c1-7f0db71cc8a2: Icon # Icon
    32ebdec2-6e1e-46de-8c50-f18ddfbde228: 'Local Salon Content' # Local Salon Content
    38dc9635-7a7d-484c-bffc-96bf8c1ae3e3: 'Local Salons' # Local Salons
    52a63f08-5474-4cca-bc26-0d405b83ba7a: Simple # Simple
    57e46740-bfbe-4ccd-a49e-a9b613807a45: Lightswitch # Lightswitch
    64b3113c-4c07-47b2-bed6-94149314dc80: 'RTE - Text Only' # RTE - Text Only
    64d5fb1c-b9f8-460b-9c44-c9b292e8afc0: 'Photo Collage' # Photo Collage
    65abf317-e671-4d15-b847-6c77d624328a: 'Recruitment Process' # Recruitment Process
    067dc454-76f0-47fe-8a39-6380da7fc55e: SEO # SEO
    68ba543b-e8a1-466a-9338-af5cc2d458dd: Images # Images
    69dd3687-8b36-4e2c-b797-7ed6b86a8ee8: 'Our People Page' # Our People Page
    91fc3931-66af-4a46-90cf-b0ede459b66b: 'Local Salons' # Local Salons
    094e4fb6-0820-4cba-ba7d-ff6a1f41529b: 'Image Cards Section' # Image Cards Section
    96afe1ed-1049-4810-88fc-7c06133c2e03: 'RTE - Full' # RTE - Full
    96eb5731-03f7-428c-97b7-32172b537746: Card # Card
    97cdda06-67e6-4755-a9d3-2534f16a2c73: 'Salary Benefits Page' # Salary Benefits Page
    240a6aad-64e3-46ca-8126-104480673800: 'Newsletter Subscribe Section' # Newsletter Subscribe Section
    446df8be-12fb-456d-a827-6e09a5b1f15a: 'Team Section' # Team Section
    0596fc40-de8d-419a-a76d-0d5412a5f315: 'Site Globals' # Site Globals
    743ec001-12a3-48f1-8ebe-cb880deb1e5a: 'Jobs Listing' # Jobs Listing
    0760dd42-e38c-4c5c-af04-3c9b32d0b198: Team # Team
    784dddde-4bbd-4e66-b3e0-928ae791e302: 'Employee Text' # Employee Text
    812c0fbf-668a-47f6-b48f-433f3e4d5550: 'Image Cards' # Image Cards
    822d8c30-81b1-4042-b211-0f5bf17fe786: Darlington # Darlington
    925df286-518b-4bdb-a7d5-ccd461be7236: Team # Team
    1290b18c-3072-4138-8fd2-b4808503a83f: 'Text w/ Image Cards' # Text w/ Image Cards
    3777c10e-da81-4c0b-9f87-85cb8bd27b14: 'Article & News' # Article & News
    5241ddf9-1a26-4245-babb-b5b96cbea919: Durham # Durham
    6405f652-9433-4c53-9feb-e2324d8b8973: 'Content Page' # Content Page
    16675a87-08c8-4f34-b9d9-1218d1eced39: 'Benefit Pages' # Benefit Pages
    75916bae-efdb-428b-b8e2-0904b4627e76: 'Rich Text' # Rich Text
    875175ae-1cd7-4e52-82ea-3ba5a7a69033: Services # Services
    6011565c-f9ba-4a4c-8a5d-97013226a35a: 'Rollout Plans' # Rollout Plans
    20719496-58c0-4027-9186-9aea86bd4365: 'Features w/ CTAs Section' # Features w/ CTAs Section
    71388431-55ea-4c3f-a6a8-6b7a3bdd51b6: 'Video Testimonials' # Video Testimonials
    84283218-957b-4c9d-a1d9-ed73c435cde8: Image # Image
    87994572-cfd6-45fd-960d-a94a832a89c5: 'Employee Video' # Employee Video
    a5c4bb68-a93b-4064-94ed-c61308d2b930: 'Process Steps' # Process Steps
    a53cfce4-0998-4b8c-b0de-13a33d2f6c6e: 'Process Step' # Process Step
    a424a048-14aa-4cdc-a80e-3cbedee60726: Vacancies # Vacancies
    a879f311-1328-4f30-ac91-a12a459194b1: Pages # Pages
    aa88dbbd-c68f-44c0-bb5f-efd07e8cb367: CTA # CTA
    acb66ef8-b78e-4e0f-8040-e9fd7a84dc02: Apply # Apply
    ad8ae5e8-8807-4a2e-98bf-1b57748f7b72: 'Article/News Categories' # Article/News Categories
    afc98222-b9e8-4b9c-9a97-4d7ac76eb77f: 'Job Grid' # Job Grid
    b034d3bd-57dd-43c8-824b-e15bac0ee2e4: 'Article Categories' # Article Categories
    b3e9cdaa-43c9-498a-bbab-42cad816e875: Button # Button
    b7b36318-f071-4097-8730-a77ac7b5fe96: 'RTE - Simple Text' # RTE - Simple Text
    b9fcd03b-b339-45a2-a20c-a1ad70811bfb: Benefits # Benefits
    b12f7f4a-e079-45fe-9285-fdd1643c6db6: 'Author Thumb' # Author Thumb
    b30c7324-129a-47c8-b2a1-109d011ee287: 'Services Section' # Services Section
    b298e3da-2b5d-47a1-a1c7-24bf013ae262: 'Trade Test Process' # Trade Test Process
    b421bd1c-2476-4b2e-99f3-997e88b3f7df: 'Our People' # Our People
    c5ad5b48-ebb0-4704-9f40-8a12ff6648e2: 'Site Uploads' # Site Uploads
    c9c531be-d612-42d8-9bf3-a7acc503af2d: 'Job Benefits' # Job Benefits
    c15e8516-7e75-4c32-b6a2-98d2d78dba3e: Cards # Cards
    c94b79ec-0b53-47e3-8ef9-4b8562781846: Home # Home
    c97c5e93-fa46-4607-9bb5-73aab466f0bb: 'Job Thumb' # Job Thumb
    c711f164-bd59-4d27-910c-94eb0fc77d2a: 'Benefit Pages' # Benefit Pages
    c8305476-25b6-417d-9392-07aa86e5d502: 'Recruitment Process' # Recruitment Process
    cf0e65ca-30ab-4935-927a-fcd42d5112b6: Video # Video
    cf90e322-6859-4622-bfcb-61a01096cdc9: 'Salary & Benefits' # Salary & Benefits
    cfe1f9f6-7ba4-4eec-af4d-d8fcd8687f6d: 'Text / Image Cards' # Text / Image Cards
    d1fc2d2e-2b87-44e9-83dc-bf4de8243e18: 'Text Image Grid' # Text Image Grid
    d6b4db56-93c1-47b7-99a7-d1b453b1c281: CTAs # CTAs
    d6c8cf87-bfda-4180-803b-408375d5b40b: 'Apply Page' # Apply Page
    d8b6f4ed-eead-4f24-ad26-8f297bd97741: 'Text Only' # Text Only
    d12a0940-24db-484d-bf19-8c937a040875: 'Form Cities (with opening date)' # Form Cities (with opening date)
    d54816d2-a954-46ab-b48e-ee1b79a75db5: 'Youtube Video' # Youtube Video
    db0eba9c-e40f-4df7-a5af-e0bd0d7d46cf: 'Articles & News Section' # Articles & News Section
    dba1f4d5-7074-4028-8aa4-6b32b64e86ab: Features # Features
    dd713845-af4e-4e60-9d0a-171d3ed41bb9: 'About Us' # About Us
    df45790b-b0f0-427e-89e2-4767cbbf719c: Jobs # Jobs
    e8c8e356-5c73-4595-b2c6-b5973a67da4c: 'Holding Page' # Holding Page
    e49f78c7-9b22-409e-b03e-671922e6915f: 'Our Culture' # Our Culture
    f0f5c790-85e7-436d-9f47-3e1a7966a1b1: 'Job Type' # Job Type
    f1bd2935-9135-4dfd-aec4-e7459ca70d1d: 'Employee Speaks' # Employee Speaks
    f4a67cd2-d8bf-4d6a-9f38-4241b1f27393: Jobs # Jobs
    f5d1ded3-5a5e-400e-836c-7c4d1d346ab1: 'Trade Test Process' # Trade Test Process
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  embeddedassets:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  expanded-singles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      expandSingles: true
      redirectToEntry: true
  hyper:
    edition: standard
    enabled: true
    licenseKey: CDRRYOX785ZGO5RCDHP53TAZ
    schemaVersion: 1.0.0
  oembed:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  retcon:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: N504S2U3EOSZSRS9T1WIHJYY
    schemaVersion: 3.0.12
  servd-asset-storage:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
    settings:
      adjustFeedmeLogs: ''
      assetsEnvironment: ''
      assetsEnvironmentOverwrite: ''
      cacheClearMode: full
      clearCachesOnSave: always
      disableDynamic: ''
      disableTransforms: ''
      fsMapsEnabled: ''
      imageAutoConversion: webp
      injectCors: ''
      projectSlug: $SERVD_PROJECT_SLUG
      securityKey: $SERVD_SECURITY_KEY
      suppressWarnings: ''
      useLocalVolumes: false
  wheelform:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      cp_label: Forms
      disabled_fields: ''
      from_email: info@halohairgroup.com
      from_name: 'Halo Group'
      recaptcha_min_score: '0.5'
      recaptcha_public: ''
      recaptcha_secret: ''
      recaptcha_version: '2'
      success_message: 'Thank You! we will review your submission shortly.'
      volume_id: '1'
system:
  edition: team
  live: true
  name: 'Halo Hair Group'
  retryDuration: null
  schemaVersion: 5.5.0.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
