dateModified: 1726905132
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: '*'
      tableAttributes:
        - status
        - section
        - postDate
        - authors
        - link
      type: native
    -
      key: 'single:f4a67cd2-d8bf-4d6a-9f38-4241b1f27393' # Home
      type: native
    -
      key: 'single:0596fc40-de8d-419a-a76d-0d5412a5f315' # Site Globals
      type: native
    -
      key: 'single:0ccd9cb4-cb6f-44da-b932-3dae09c2db79' # Holding Page
      type: native
    -
      key: 'section:743ec001-12a3-48f1-8ebe-cb880deb1e5a' # Jobs
      type: native
    -
      key: 'section:38dc9635-7a7d-484c-bffc-96bf8c1ae3e3' # Rollout Plans
      type: native
email:
  fromEmail: $SERVD_SMTP_USERNAME
  fromName: 'Halo Hair Group'
  replyToEmail: null
  template: null
  transportSettings:
    host: $SERVD_SMTP_HOSTNAME
    password: $SERVD_SMTP_PASSWORD
    port: '2525'
    useAuthentication: '1'
    username: $SERVD_SMTP_USERNAME
  transportType: craft\mail\transportadapters\Smtp
fs:
  uploads:
    hasUrls: true
    name: Uploads
    settings:
      cdnUrlPattern: ''
      customSubfolder: ''
      makeUploadsPublic: true
      optimisePrefix: ''
      optimiseUrlPattern: ''
      projectSlug: ''
      securityKey: ''
      subfolder: local/
    type: servd\AssetStorage\AssetsPlatform\Fs
    url: 'https://halo-hair.files.svdcdn.com'
meta:
  __names__:
    0ccd9cb4-cb6f-44da-b932-3dae09c2db79: 'Holding Page' # Holding Page
    1f1a03f8-9f09-4e72-90b2-73744ea2d88c: Full # Full
    2cffa8d4-0f9f-4b73-a0b9-96d331e94d8a: 'Video Testimonial' # Video Testimonial
    2f4521a5-bf9c-4655-bd15-483fa28c005f: Year # Year
    4a757ae5-8a0f-4384-ab08-99d5e96e32dc: 'Bullet Points' # Bullet Points
    4fdc851f-7db3-4c90-880c-a187ac552886: 'Halo Hair Group' # Halo Hair Group
    5a77901a-6b9c-460b-bb5c-032b263bc717: Halo # Halo
    5b40a23e-fc7b-48ed-b092-746f8700aa48: 'Opening Month' # Opening Month
    5c1885e7-2d6a-4df5-8de7-646816d23c2a: Benefits # Benefits
    7aea93d0-d819-4905-8279-efcfd692ad42: Text # Text
    7f82abc5-4a85-431f-8ffa-c9d3452c3c4e: Phase # Phase
    8c2ae0e0-bafc-45d7-ac4b-2de4bd0cabec: 'Text Area' # Text Area
    8eb9df4d-b6b1-4331-9b12-46c97ce4b33e: 'Site Globals' # Site Globals
    27b29006-47a2-40b1-a7c1-7f0db71cc8a2: Icon # Icon
    38dc9635-7a7d-484c-bffc-96bf8c1ae3e3: 'Rollout Plans' # Rollout Plans
    52a63f08-5474-4cca-bc26-0d405b83ba7a: Simple # Simple
    64b3113c-4c07-47b2-bed6-94149314dc80: 'RTE - Text Only' # RTE - Text Only
    067dc454-76f0-47fe-8a39-6380da7fc55e: SEO # SEO
    96afe1ed-1049-4810-88fc-7c06133c2e03: 'RTE - Full' # RTE - Full
    0596fc40-de8d-419a-a76d-0d5412a5f315: 'Site Globals' # Site Globals
    743ec001-12a3-48f1-8ebe-cb880deb1e5a: Jobs # Jobs
    75916bae-efdb-428b-b8e2-0904b4627e76: 'Rich Text' # Rich Text
    6011565c-f9ba-4a4c-8a5d-97013226a35a: 'Rollout Plans' # Rollout Plans
    71388431-55ea-4c3f-a6a8-6b7a3bdd51b6: 'Video Testimonials' # Video Testimonials
    84283218-957b-4c9d-a1d9-ed73c435cde8: Image # Image
    aa88dbbd-c68f-44c0-bb5f-efd07e8cb367: CTA # CTA
    b9fcd03b-b339-45a2-a20c-a1ad70811bfb: Benefits # Benefits
    c5ad5b48-ebb0-4704-9f40-8a12ff6648e2: 'Site Uploads' # Site Uploads
    c94b79ec-0b53-47e3-8ef9-4b8562781846: Home # Home
    cf0e65ca-30ab-4935-927a-fcd42d5112b6: Video # Video
    d8b6f4ed-eead-4f24-ad26-8f297bd97741: 'Text Only' # Text Only
    d12a0940-24db-484d-bf19-8c937a040875: 'Form Cities (with opening date)' # Form Cities (with opening date)
    d54816d2-a954-46ab-b48e-ee1b79a75db5: 'Youtube Video' # Youtube Video
    df45790b-b0f0-427e-89e2-4767cbbf719c: Jobs # Jobs
    e8c8e356-5c73-4595-b2c6-b5973a67da4c: 'Holding Page' # Holding Page
    f0f5c790-85e7-436d-9f47-3e1a7966a1b1: 'Job Type' # Job Type
    f4a67cd2-d8bf-4d6a-9f38-4241b1f27393: Home # Home
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  embeddedassets:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  expanded-singles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      expandSingles: true
      redirectToEntry: true
  hyper:
    edition: standard
    enabled: true
    licenseKey: CDRRYOX785ZGO5RCDHP53TAZ
    schemaVersion: 1.0.0
  image-optimize:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  image-resizer:
    edition: standard
    enabled: false
    schemaVersion: 2.0.0
  oembed:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  seomatic:
    edition: standard
    enabled: true
    licenseKey: N504S2U3EOSZSRS9T1WIHJYY
    schemaVersion: 3.0.12
  servd-asset-storage:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
    settings:
      adjustFeedmeLogs: ''
      assetsEnvironment: ''
      assetsEnvironmentOverwrite: ''
      cacheClearMode: full
      clearCachesOnSave: always
      disableDynamic: ''
      disableTransforms: ''
      fsMapsEnabled: ''
      imageAutoConversion: webp
      injectCors: ''
      projectSlug: $SERVD_PROJECT_SLUG
      securityKey: $SERVD_SECURITY_KEY
      suppressWarnings: ''
      useLocalVolumes: false
  wheelform:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      cp_label: Forms
      disabled_fields: ''
      from_email: info@halohairgroup.com
      from_name: 'Halo Group'
      recaptcha_min_score: '0.5'
      recaptcha_public: ''
      recaptcha_secret: ''
      recaptcha_version: '2'
      success_message: 'Thank You! we will review your submission shortly.'
      volume_id: '1'
system:
  edition: team
  live: true
  name: 'Halo Hair Group'
  retryDuration: null
  schemaVersion: 5.3.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
