dateModified: 1724307098
email:
  fromEmail: bhashkar007@gmail.com
  fromName: Halo
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    4fdc851f-7db3-4c90-880c-a187ac552886: Halo # Halo
    5a77901a-6b9c-460b-bb5c-032b263bc717: Halo # Halo
system:
  edition: team
  live: true
  name: 'Halo Hair'
  retryDuration: null
  schemaVersion: 5.3.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
