defaultPlacement: end
enableVersioning: true
entryTypes:
  - 1e7969e0-4dc9-4153-886d-a1985e4b0766 # About Us
handle: aboutUs
maxAuthors: 1
name: 'About Us'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  4fdc851f-7db3-4c90-880c-a187ac552886: # Halo Hair Group
    enabledByDefault: true
    hasUrls: true
    template: _sections/about-us/_entry.twig
    uriFormat: jobs/about-us
type: single
