defaultPlacement: end
enableVersioning: true
entryTypes:
  - d6c8cf87-bfda-4180-803b-408375d5b40b # Apply
handle: apply
maxAuthors: 1
name: Apply
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  4fdc851f-7db3-4c90-880c-a187ac552886: # Halo Hair Group
    enabledByDefault: true
    hasUrls: true
    template: _sections/apply/_entry.twig
    uriFormat: jobs/apply
type: single
