defaultPlacement: end
enableVersioning: true
entryTypes:
  - 3b0d478f-3b10-4424-9f3c-fd2c2d304e29 # Article & News
handle: articleNews
maxAuthors: 1
name: 'Article & News'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  4fdc851f-7db3-4c90-880c-a187ac552886: # Jobs
    enabledByDefault: true
    hasUrls: true
    template: article-news/_entry.twig
    uriFormat: 'article-news/{slug}'
type: channel
