defaultPlacement: end
enableVersioning: true
entryTypes:
  - b034d3bd-57dd-43c8-824b-e15bac0ee2e4 # Article Categories
handle: articleCategories
maxAuthors: 1
name: 'Article Categories'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  4fdc851f-7db3-4c90-880c-a187ac552886: # Halo Hair Group
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 0b8dc63e-3113-4ca6-9278-5229c37535c2
type: structure
