defaultPlacement: end
enableVersioning: true
entryTypes:
  - c711f164-bd59-4d27-910c-94eb0fc77d2a # Benefit Pages
handle: jobBenefits
maxAuthors: 1
name: 'Job Benefits'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  2d9f82e7-e967-491c-8b4c-b45ce52ab7e1: # Jobs
    enabledByDefault: true
    hasUrls: true
    template: _sections/job-benefits/_entry.twig
    uriFormat: 'benefits/{slug}'
type: channel
