defaultPlacement: end
enableVersioning: true
entryTypes:
  - c94b79ec-0b53-47e3-8ef9-4b8562781846 # Home
handle: jobs
maxAuthors: 1
name: 'Jobs Home'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  2d9f82e7-e967-491c-8b4c-b45ce52ab7e1: # Jobs
    enabledByDefault: true
    hasUrls: true
    template: _sections/jobs/_entry.twig
    uriFormat: __home__
type: single
