defaultPlacement: end
enableVersioning: true
entryTypes:
  - 6011565c-f9ba-4a4c-8a5d-97013226a35a # Local Salon
handle: localSalons
maxAuthors: 1
name: 'Local Salons'
propagationMethod: all
siteSettings:
  4fdc851f-7db3-4c90-880c-a187ac552886: # Jobs
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: a8456fbc-8c30-4d86-914c-69ffa5ca828f
type: structure
