defaultPlacement: end
enableVersioning: true
entryTypes:
  - 8bcdb7ac-055d-4548-9cda-bd6a68b501d5 # Our Culture Page
handle: ourCulture
maxAuthors: 1
name: 'Our Culture'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  4fdc851f-7db3-4c90-880c-a187ac552886: # Halo Hair Group
    enabledByDefault: true
    hasUrls: true
    template: _sections/our-culture/_entry.twig
    uriFormat: our-culture
type: single
