defaultPlacement: end
enableVersioning: true
entryTypes:
  - 69dd3687-8b36-4e2c-b797-7ed6b86a8ee8 # Our People Page
handle: ourPeople
maxAuthors: 1
name: 'Our People'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  4fdc851f-7db3-4c90-880c-a187ac552886: # Jobs
    enabledByDefault: true
    hasUrls: true
    template: _sections/our-people/_entry.twig
    uriFormat: our-people
type: single
