defaultPlacement: end
enableVersioning: true
entryTypes:
  - 6011565c-f9ba-4a4c-8a5d-97013226a35a # Rollout Plans
handle: rolloutPlans
maxAuthors: 1
name: 'Rollout Plans'
propagationMethod: all
siteSettings:
  4fdc851f-7db3-4c90-880c-a187ac552886: # Halo Hair Group
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: a8456fbc-8c30-4d86-914c-69ffa5ca828f
type: structure
