defaultPlacement: end
enableVersioning: true
entryTypes:
  - 97cdda06-67e6-4755-a9d3-2534f16a2c73 # Salary Benefits
handle: salaryBenefits
maxAuthors: 1
name: 'Salary & Benefits'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  4fdc851f-7db3-4c90-880c-a187ac552886: # Halo Hair Group
    enabledByDefault: true
    hasUrls: true
    template: _sections/salary-benefits/_entry.twig
    uriFormat: jobs/salary-benefits
type: single
