defaultPlacement: end
enableVersioning: true
entryTypes:
  - 07edd6a8-1941-47c3-8535-ccc56f465ac0 # Services
handle: services
maxAuthors: 1
name: Services
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  4fdc851f-7db3-4c90-880c-a187ac552886: # Halo Hair Group
    enabledByDefault: true
    hasUrls: true
    template: services/_entry.twig
    uriFormat: 'services/{slug}'
structure:
  maxLevels: 1
  uid: 7756dbe0-dc64-4ddf-85a5-f5e3e3be3e00
type: structure
