defaultPlacement: end
enableVersioning: true
entryTypes:
  - 0760dd42-e38c-4c5c-af04-3c9b32d0b198 # Team
handle: team
maxAuthors: 1
name: Team
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  4fdc851f-7db3-4c90-880c-a187ac552886: # Halo Hair Group
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
