defaultPlacement: end
enableVersioning: true
entryTypes:
  - 8f985adb-f8ad-4b76-acd5-678c5e7c8e6d # Vacancies Page
handle: vacancies
maxAuthors: 1
name: Vacancies
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  4fdc851f-7db3-4c90-880c-a187ac552886: # Jobs
    enabledByDefault: true
    hasUrls: true
    template: _sections/vacancies/_entry.twig
    uriFormat: vacancies
type: single
